# Generated by Django 3.1.1 on 2020-10-04 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('department', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=50)),
                ('course_number', models.CharField(max_length=100)),
                ('section_number', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=200)),
                ('a1', models.IntegerField()),
                ('a2', models.IntegerField()),
                ('a3', models.IntegerField()),
                ('b1', models.IntegerField()),
                ('b2', models.IntegerField()),
                ('b3', models.IntegerField()),
                ('c1', models.IntegerField()),
                ('c2', models.IntegerField()),
                ('c3', models.IntegerField()),
                ('d1', models.IntegerField()),
                ('d2', models.IntegerField()),
                ('d3', models.IntegerField()),
                ('f', models.IntegerField()),
                ('total', models.IntegerField()),
                ('p', models.IntegerField(null=True)),
                ('np', models.IntegerField(null=True)),
                ('incomplete', models.IntegerField(null=True)),
                ('average', models.FloatField()),
                ('letter_average', models.CharField(default='', max_length=2)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.course')),
            ],
            options={
                'db_table': 'catalog_grade',
            },
        ),
    ]
