# Generated by Django 3.1.1 on 2020-10-25 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='total',
            new_name='graded_total',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='incomplete',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='letter_average',
        ),
    ]
