# Generated by Django 3.1.1 on 2020-10-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_auto_20201025_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='instructors',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
