# Generated by Django 3.1.1 on 2020-10-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_auto_20201025_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='average',
            field=models.FloatField(default=0.0),
        ),
    ]
