# Generated by Django 3.1.1 on 2020-10-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_auto_20201025_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='average',
            field=models.FloatField(default=-1.0),
        ),
    ]
