# Generated by Django 3.1.1 on 2020-11-11 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0006_auto_20201025_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='instructors',
        ),
    ]
