# Generated by Django 3.1.1 on 2020-11-11 01:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0006_auto_20201025_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='instructors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
