# Grafana Loki - log aggregation
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  labels:
    {{- include "bt-observability.lokiLabels" . | nindent 4 }}
data:
  loki.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
    common:
      ring:
        kvstore:
          store: inmemory
        replication_factor: 1
      path_prefix: /loki
    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      wal:
        enabled: true
        dir: /loki/wal
    distributor:
      ring:
        kvstore:
          store: inmemory
    schema_config:
      configs:
        - from: "2024-01-01"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    storage_config:
      tsdb_shipper:
        active_index_directory: /loki/tsdb-index
        cache_location: /loki/tsdb-cache
      filesystem:
        directory: /loki/chunks
    compactor:
      working_directory: /loki/tsdb-compactor
    limits_config:
      allow_structured_metadata: true
      volume_enabled: true

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
  labels:
    {{- include "bt-observability.lokiLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.loki.storage.size }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  labels:
    {{- include "bt-observability.lokiLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
  template:
    metadata:
      labels:
        {{- include "bt-observability.lokiLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/loki.yaml") . | sha256sum }}
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - name: loki
          image: {{ .Values.loki.image }}
          args:
            - "-config.file=/etc/loki/loki.yaml"
          ports:
            - name: http
              containerPort: 3100
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
          resources:
            {{- toYaml .Values.loki.resources | nindent 12 }}
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
          volumeMounts:
            - name: config
              mountPath: /etc/loki
              readOnly: true
            - name: data
              mountPath: /loki
          readinessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 30
      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: data
          persistentVolumeClaim:
            claimName: loki-data

---

apiVersion: v1
kind: Service
metadata:
  name: loki
  labels:
    {{- include "bt-observability.lokiLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: loki
  ports:
    - name: http
      port: 3100
      targetPort: 3100
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: 9095
      protocol: TCP
