apiVersion: v1
kind: PersistentVolume
metadata: 
  name: prometheus-pv
spec:
  storageClassName: manual
  capacity: 
    storage: {{.Values.prometheus.storage.size}}
  accessModes: 
    - ReadWriteOnce
  hostPath: 
    path: /data/prometheus

---

apiVersion: v1
kind: PersistentVolume
metadata: 
  name: tempo-pv
spec:
  storageClassName: manual
  capacity: 
    storage: {{.Values.tempo.storage.size}}
  accessModes: 
    - ReadWriteOnce
  hostPath: 
    path: /data/tempo

---

apiVersion: v1
kind: PersistentVolume
metadata: 
  name: loki-pv
spec:
  storageClassName: manual
  capacity: 
    storage: {{.Values.loki.storage.size}}
  accessModes: 
    - ReadWriteOnce
  hostPath: 
    path: /data/loki


---

apiVersion: v1
kind: PersistentVolume
metadata: 
  name: grafana-pv
spec:
  storageClassName: manual
  capacity: 
    storage: {{.Values.grafana.storage.size}}
  accessModes: 
    - ReadWriteOnce
  hostPath: 
    path: /data/grafana