all:
	lessc --clean-css utils.less utils.css
	lessc --clean-css base.less base.css
	lessc --clean-css contact.less contact.css
	lessc --clean-css schedule/schedule.less schedule/schedule.css
	lessc --clean-css catalog/catalog.less catalog/catalog.css
	lessc --clean-css catalog/course_box.less catalog/course_box.css
	lessc --clean-css data/data.less data/data.css
	lessc --clean-css data/grades.less data/grades.css
	lessc --clean-css data/enrollment.less data/enrollment.css
	lessc --clean-css common/berkeleytime-box.less common/berkeleytime-box.css
	lessc --clean-css campus/campus.less campus/campus.css
	lessc --clean-css common/welcome.less common/welcome.css
	lessc --clean-css about.less about.css
	lessc --clean-css register.less register.css
	lessc --clean-css team/photos.less team/photos.css
