# Generated by Django 3.1.1 on 2020-10-04 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True)),
                ('course_number', models.CharField(blank=True, max_length=10, null=True)),
                ('units', models.CharField(blank=True, max_length=1024, null=True)),
                ('hours', models.CharField(blank=True, max_length=1024, null=True)),
                ('cs_course_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('grading', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('previously', models.CharField(blank=True, max_length=1024, null=True)),
                ('final_exam_status', models.CharField(blank=True, max_length=1024, null=True)),
                ('credit_restrictions', models.CharField(blank=True, max_length=1024, null=True)),
                ('primary_kind', models.CharField(blank=True, max_length=20, null=True)),
                ('favorite_count', models.IntegerField(default=0)),
                ('prerequisites', models.TextField(blank=True, null=True)),
                ('grade_average', models.FloatField(default=-1, null=True)),
                ('letter_average', models.CharField(blank=True, max_length=2, null=True)),
                ('enrolled_percentage', models.FloatField(default=-1)),
                ('open_seats', models.IntegerField(default=-1)),
                ('enrolled', models.IntegerField(default=-1)),
                ('enrolled_max', models.IntegerField(default=-1)),
                ('waitlisted', models.IntegerField(default=-1)),
                ('has_enrollment', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalog_course',
                'unique_together': {('abbreviation', 'course_number')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True)),
                ('course_number', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('semester', models.CharField(blank=True, max_length=20, null=True)),
                ('ccn', models.CharField(blank=True, max_length=50, null=True)),
                ('course_title', models.CharField(blank=True, max_length=200, null=True)),
                ('days', models.CharField(blank=True, max_length=20, null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('final_end', models.DateTimeField(blank=True, null=True)),
                ('final_start', models.DateTimeField(blank=True, null=True)),
                ('final_day', models.CharField(blank=True, max_length=1, null=True)),
                ('instructor', models.CharField(blank=True, max_length=300, null=True)),
                ('kind', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('location_name', models.CharField(blank=True, max_length=300, null=True)),
                ('note', models.TextField(null=True)),
                ('rank', models.IntegerField(null=True)),
                ('restrictions', models.TextField(null=True)),
                ('section_number', models.CharField(blank=True, max_length=20, null=True)),
                ('suffix', models.CharField(blank=True, max_length=5, null=True)),
                ('units', models.CharField(blank=True, max_length=50, null=True)),
                ('instruction_mode', models.CharField(blank=True, max_length=128, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('enrolled', models.IntegerField(null=True)),
                ('enrolled_max', models.IntegerField(null=True)),
                ('waitlisted', models.IntegerField(null=True)),
                ('waitlisted_max', models.IntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.course')),
                ('related', models.ManyToManyField(related_name='_section_related_+', to='catalog.Section')),
            ],
            options={
                'db_table': 'catalog_section',
            },
        ),
    ]
