# Generated by Django 3.1.1 on 2020-10-17 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('department', models.CharField(max_length=150)),
                ('abbreviation', models.CharField(max_length=20)),
                ('course_number', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('units', models.CharField(max_length=20)),
                ('prerequisites', models.TextField()),
                ('grade_average', models.FloatField(default=-1, null=True)),
                ('letter_average', models.CharField(max_length=2)),
                ('has_enrollment', models.BooleanField(default=False)),
                ('enrolled', models.IntegerField(default=-1)),
                ('enrolled_max', models.IntegerField(default=-1)),
                ('enrolled_percentage', models.FloatField(default=-1)),
                ('waitlisted', models.IntegerField(default=-1)),
                ('open_seats', models.IntegerField(default=-1)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'course',
                'unique_together': {('abbreviation', 'course_number')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=20)),
                ('course_number', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('semester', models.CharField(max_length=20)),
                ('course_title', models.CharField(max_length=200)),
                ('section_number', models.CharField(max_length=20)),
                ('ccn', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('days', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('final_day', models.CharField(max_length=1)),
                ('final_end', models.DateTimeField(null=True)),
                ('final_start', models.DateTimeField(null=True)),
                ('instructor', models.CharField(max_length=300)),
                ('disabled', models.BooleanField(default=False)),
                ('location_name', models.CharField(max_length=300)),
                ('instruction_mode', models.CharField(max_length=128)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('enrolled', models.IntegerField(null=True)),
                ('enrolled_max', models.IntegerField(null=True)),
                ('waitlisted', models.IntegerField(null=True)),
                ('waitlisted_max', models.IntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.course')),
            ],
            options={
                'db_table': 'section',
            },
        ),
    ]
