# Generated by Django 3.1.1 on 2020-10-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['disabled'], name='section_disable_971a48_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['is_primary'], name='section_is_prim_4ca849_idx'),
        ),
    ]
