# Generated by Django 3.1.1 on 2020-10-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20201028_1114'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['abbreviation', 'course_number'], name='section_abbrevi_9a32f1_idx'),
        ),
    ]
