# Generated by Django 3.1.1 on 2020-10-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201028_1312'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['kind'], name='section_kind_b153d3_idx'),
        ),
    ]
