# Generated by Django 3.1.1 on 2020-11-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201028_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cross_listing',
            field=models.ManyToManyField(related_name='_course_cross_listing_+', to='catalog.Course'),
        ),
    ]
