import { normalizeSubject } from "@repo/common";

// Maps a visual cluster to its subjects. The frontend builds the image URL from
// the cluster name. Unlisted subjects fall back to the campus default.
const CLUSTER_SUBJECTS: Record<string, string[]> = {
  math: ["MATH", "STAT", "MPS"],
  physics: ["PHYSICS"],
  astronomy: ["ASTRON"],
  chemistry: ["CHEM"],
  biology: [
    "MCELLBI",
    "INTEGBI",
    "PLANTBI",
    "BIOLOGY",
    "BIOPHY",
    "CMPBIO",
    "COMPBIO",
    "NUSCTX",
    "MBN",
  ],
  medicine: ["OPTOM", "VISSCI", "HMEDSCI", "CPH"],
  publichealth: ["PBHLTH"],
  engineering: [
    "MECENG",
    "CIVENG",
    "ELENG",
    "MATSCI",
    "NUCENG",
    "AEROENG",
    "CHMENG",
    "BIOENG",
    "INDENG",
    "ENGIN",
    "DEVENG",
    "NSE",
  ],
  computing: ["COMPSCI", "EECS", "DATA", "INFO", "DATASCI", "CDSS", "CYBER"],
  environment: ["ESPM", "EPS", "GEOG", "ENERES", "NATRES", "CSOL"],
  society: [
    "SOCIOL",
    "ANTHRO",
    "ETHSTD",
    "ASAMST",
    "CHICANO",
    "AFRICAM",
    "NATAMST",
    "GWS",
    "LGBT",
    "DISSTD",
    "QTP",
    "AMERSTD",
    "ASIANST",
    "LATAMST",
    "MESTU",
    "EUST",
    "STS",
  ],
  politics: [
    "POLSCI",
    "PUBPOL",
    "PUBAFF",
    "POLECON",
    "GPP",
    "IAS",
    "GLOBAL",
    "PACS",
    "DEVP",
    "DEVSTD",
    "DEMOG",
    "COMPSS",
  ],
  psychology: ["PSYCH", "COGSCI", "NEU", "NEUROSC"],
  economics: [
    "ECON",
    "UGBA",
    "MBA",
    "EWMBA",
    "XMBA",
    "PHDBA",
    "MFE",
    "ARESEC",
    "ENVECON",
  ],
  law: ["LAW", "LEGALST"],
  architecture: ["ARCH", "CYPLAN", "ENVDES", "RDEV", "LDARCH", "GMS"],
  education: ["EDUC", "SOCWEL", "EDSTEM", "SCMATHE", "GSPDP"],
  literature: [
    "ENGLISH",
    "COMLIT",
    "CRWRIT",
    "RHETOR",
    "COLWRIT",
    "CRITTH",
    "FOLKLOR",
    "MEDST",
    "HUM",
    "DIGHUM",
    "BUDDSTD",
    "RELIGST",
    "STRELIG",
    "JEWISH",
  ],
  language: [
    "FRENCH",
    "SPANISH",
    "ITALIAN",
    "PORTUG",
    "CATALAN",
    "GERMAN",
    "DUTCH",
    "SCANDIN",
    "DANISH",
    "SWEDISH",
    "NORWEGN",
    "FINNISH",
    "ICELAND",
    "SLAVIC",
    "RUSSIAN",
    "POLISH",
    "UKRAINI",
    "CZECH",
    "BOSCRSR",
    "HUNGARI",
    "CELTIC",
    "CHINESE",
    "JAPAN",
    "KOREAN",
    "EALANG",
    "SASIAN",
    "SSEASN",
    "SEASIAN",
    "VIETNMS",
    "FILIPN",
    "INDONES",
    "THAI",
    "KHMER",
    "BURMESE",
    "MONGOLN",
    "TIBETAN",
    "HINDI",
    "PUNJABI",
    "TAMIL",
    "TELUGU",
    "BANGLA",
    "URDU",
    "SANSKR",
    "ARABIC",
    "PERSIAN",
    "IRANIAN",
    "ARMENI",
    "TURKISH",
    "HEBREW",
    "YIDDISH",
    "SEMITIC",
    "LINGUIS",
    "LANPRO",
    "MELC",
  ],
  history: [
    "HISTORY",
    "CLASSIC",
    "AGRS",
    "AHMA",
    "EGYPT",
    "CUNEIF",
    "LATIN",
    "GREEK",
    "MDGRK",
  ],
  philosophy: ["PHILOS"],
  art: ["ART", "HISTART", "VISSTD", "DESINV"],
  music: ["MUSIC"],
  performance: ["THEATER", "FILM"],
  media: ["JOURN", "MEDIAST", "NWMEDIA"],
};

const SUBJECT_TO_CLUSTER: Record<string, string> = {};
for (const [cluster, subjects] of Object.entries(CLUSTER_SUBJECTS)) {
  for (const subject of subjects) {
    SUBJECT_TO_CLUSTER[subject] = cluster;
  }
}

export function clusterForSubject(subject: string): string | null {
  return SUBJECT_TO_CLUSTER[normalizeSubject(subject)] ?? null;
}
