# path in host machine. should depend on environment and be different for each mongo pod.
hostPath: /data/prod/db

mongodb:
  # Use bitnamilegacy registry (Bitnami moved older image tags there)
  image:
    registry: docker.io
    repository: bitnamilegacy/mongodb
    tag: 7.0.5-debian-11-r5

  commonLabels:
    env: prod

  architecture: replicaset
  arbiter:
    enabled: false
  replicaCount: 1

  auth:
    enabled: false

  persistence:
    storageClass: manual

    # path in pod. should be same for all mongo pods.
    size: 10Gi

  # required for persistence. without, data is not saved across pod restarts.
  volumePermissions:
    enabled: true
    image:
      registry: docker.io
      repository: bitnamilegacy/os-shell
      tag: "11"
