default_install_hook_types: [pre-push]
repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: npx prettier --check
        language: system
        files: \.(ts|tsx)$
        stages: [pre-push]
        fail_fast: true
      - id: lint
        name: lint
        entry: npm run lint
        language: system
        stages: [pre-push]
        fail_fast: true
        pass_filenames: false
