kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dockersec-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: jenkins-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi