apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cluster-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 11m
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - www.berkeleytime.com
    - berkeleytime.com
    - staging.berkeleytime.com
    - jenkins.berkeleytime.com
    - kibana.berkeleytime.com
    secretName: letsencrypt-bt
  rules:
  - host: berkeleytime.com
    http:
      paths:
      - path: /api/
        backend:
          serviceName: berkeleytime-prod-svc
          servicePort: 5000
      - path: /
        backend:
          serviceName: frontend-prod-svc
          servicePort: 3000
  - host: www.berkeleytime.com
    http:
      paths:
      - path: /api/
        backend:
          serviceName: berkeleytime-prod-svc
          servicePort: 5000
      - path: /
        backend:
          serviceName: frontend-prod-svc
          servicePort: 3000
  - host: staging.berkeleytime.com
    http:
      paths:
      - path: /api/
        backend:
          serviceName: berkeleytime-stage-svc
          servicePort: 5000
      - path: /
        backend:
          serviceName: frontend-stage-svc
          servicePort: 3000
  - host: jenkins.berkeleytime.com
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins-svc
          servicePort: 9000
