kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: jenkins-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  zone: us-west2-a
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: jenkins-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rdir-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: jenkins-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  ports:
  - name: http-jenkins-port
    port: 9000
    targetPort: 8080
  type: ClusterIP
  selector:
    appName: jenkins-dep
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-dep
  namespace: default
  labels:
    appName: jenkins-dep
spec:
  selector:
    matchLabels:
      appName: jenkins-dep
  replicas: 1
  template:
    metadata:
      labels:
        appName: jenkins-dep
    spec:
      volumes:
        - name: jenkins-pv-storage
          persistentVolumeClaim:
           claimName: jenkins-pv-claim
        - name: rdir-pv-storage
          persistentVolumeClaim:
           claimName: rdir-pv-claim
        - name: dind-storage
          emptyDir: {}
      containers:
      - name: jenkins-dep
        image: hantaowang/btjenkins:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
        - name: JAVA_OPTS
          value: -Dhudson.model.DirectoryBrowserSupport.CSP=
        volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-pv-storage
          - mountPath: /root
            name: rdir-pv-storage
      - name: dind
        image: docker:18.09-dind
        securityContext:
          privileged: true
        volumeMounts:
          - name: dind-storage
            mountPath: /var/lib/docker
        