# WARNING: DO NOT DELETE
# These objects are separate from jenkins-deploy because the persistent volumes
# backing Jenkins will be deleted if these are deleted. If
# jenkins-deploy is accidentally removed, the PVCs and PVs will remain as long
# as these objects are not removed as well. There is no good reason to delete
# these.
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: jenkins-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  zone: us-west2-a
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: jenkins-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rdir-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: jenkins-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi