info:
  unique_name: "DesignApp"
  public_name: Fall 2020 Product Designer Application
  description:
  googlesheet_link: "https://docs.google.com/spreadsheets/d/1qxw97YJKaRlLAoeGZ6kD4y8tAEXFbvxM4iYp5abv5dc/edit"
  drive_folder_name: "DesignResumes"
questions:
  - title: "Email Address"
    type: "short"
    placeholder: "example@berkeley.edu"
    format: "email"
    required: True
  - title: "Full Name"
    type: "short"
    placeholder: "Jennifer Aniston"
    required: True
  - title: "Current Year"
    type: "multiple_choice"
    placeholder: "Choose an option"
    required: True
    choices:
      - Freshman
      - Sophomore
      - Junior
      - Senior
      - Super Senior
      - Graduate Student
  - title: "Resume"
    description: "PDF Only"
    placeholder: "Upload a File"
    type: "file"
    accept: ".pdf"
    required: True
  - title: "GitHub Link"
    type: "short"
    placeholder: "github.com/..."
  - title: "Portfolio/Personal Website"
    type: "short"
    placeholder: "myportfolio.me/..."
  - title: "LinkedIn Link"
    type: "short"
    placeholder: "linkedin.com/in/..."
  - title: "Any other socials you’d like us to see!"
    type: "short"
    placeholder: "twitter.com/..."
  - title: "Technical Experience and Familiarity"
    description: "Check the tools that you are proficient at using"
    type: "multiple_select"
    required: True
    choices:
      - Figma
      - Sketch
      - Illustrator
      - Adobe XD
      - Any graphic design tool
  - title: "Why are you interested in working for Berkeleytime?"
    type: "long"
    required: True
  - title: "What do you hope to get out of your experience?"
    type: "long"
    required: True
  - title: "What ideas do you have for contributing to Berkeleytime?"
    type: "long"
    required: True
  - title: "Please list class you are taking and your other commitments for this semester. "
    type: "long"
    required: True
  - title: "Describe your web design or web development experience, if any."
    type: "long"
    required: True
  - title: "I am able to meet weekly on Sundays 4-6pm"
    type: "multiple_choice"
    placeholder: "Choose an option"
    required: True
    choices:
      - "Yes"
      - "No"
