info:
  unique_name: "DesignApp"
  public_name: 2020-21 Design + Marketing Application
  description: |-
    Apply to be a product designer or marketing associate in OCTO.
  googlesheet_link: "https://docs.google.com/spreadsheets/d/1qxw97YJKaRlLAoeGZ6kD4y8tAEXFbvxM4iYp5abv5dc/edit"
  drive_folder_name: "DesignResumes"
  close_on: "2020-09-05 23:59:59 -0700"
questions:
  - title: "Email Address"
    type: "short"
    placeholder: "example@berkeley.edu"
    format: "email"
    required: True
  - title: "Full Name"
    type: "short"
    placeholder: "Jennifer Aniston"
    required: True
  - title: "Current Year"
    type: "multiple_choice"
    placeholder: "Choose an option"
    required: True
    choices:
      - Freshman
      - Sophomore
      - Junior
      - Senior
      - Super Senior
      - Graduate Student
  - title: "All Fall 2020 courses (technical + nontechnical)"
    type: "short"
    placeholder: "CS61A, EE16A, English R1B"
    required: True
  - title: "All Fall 2020 extracurricular commitments"
    type: "short"
    placeholder: "Insert x club, research, or job"
    required: True
  - title: "Which positions are you applying for?"
    placeholder: "1st choice"
    type: "multiple_choice"
    required: True
    gap: False
    choices:
      - Product Designer
      - Marketing Associate
      - N/A
  - placeholder: "2nd choice"
    type: "multiple_choice"
    choices:
      - Product Designer
      - Marketing Associate
      - N/A
  - title: "Which teams are you applying for?"
    placeholder: "1st choice"
    type: "multiple_choice"
    required: True
    gap: False
    choices:
      - Berkeleytime
      - Beehive
      - Berkeley Mobile
      - N/A
  - placeholder: "2nd choice"
    type: "multiple_choice"
    gap: False
    choices:
      - Berkeleytime
      - Beehive
      - Berkeley Mobile
      - N/A
  - placeholder: "3rd choice"
    type: "multiple_choice"
    choices:
      - Berkeleytime
      - Beehive
      - Berkeley Mobile
      - N/A
  - title: "Resume"
    description: 
      "PDF Only."
    placeholder: "Upload a File"
    type: "file"
    accept: ".pdf"
    required: True
  - title: "GitHub Link"
    type: "short"
    placeholder: "github.com/..."
  - title: "Portfolio/Personal Website"
    description: "This is highly encouraged and a huge component of our selection process. Feel free to put a Google Drive link or any medium that displays your work."
    type: "short"
    placeholder: "myportfolio.me/..."
  - title: "Technical Experience and Familiarity"
    description: "Check the tools that you are proficient at using"
    type: "multiple_select"
    required: True
    choices:
      - Figma
      - Sketch
      - Illustrator
      - Adobe XD
      - Other / Not Listed Above
  - title: "Berkeleytime applicants: I am able to meet weekly on Sundays 4-6PM PST"
    description: "This is a hard requirement to join Berkeleytime. If you are not available you will not be considered for this team."
    type: "multiple_choice"
    required: True
    placeholder: "Choose an option"
    choices:
      - "Yes"
      - "No"
      - "Not applying to Berkeleytime"
  - title: "Choose a product that you think is well-designed, explain why it has a good user experience, and explain how you would apply this to an OCTO product."
    description: "Max 200 words."
    type: "long"
    required: True
  
  
