info:
  unique_name: "EngineeringApp"
  public_name: 2020-21 Engineering Application
  description: |-
    Apply to be a mobile, frontend, or backend engineer in OCTO. 

  googlesheet_link: "https://docs.google.com/spreadsheets/d/1EJrToZsA5Ny-QUcBKjHCERpcP2ER51L3uaXGzdPnS3M/edit"
  drive_folder_name: "EngineeringResumes"
questions:
  - title: "Email Address"
    type: "short"
    placeholder: "example@berkeley.edu"
    format: "email"
    required: True
  - title: "Full Name"
    type: "short"
    placeholder: "Jennifer Aniston"
    required: True
  - title: "Current Year"
    type: "multiple_choice"
    placeholder: "Choose an option"
    required: True
    choices:
      - Freshman
      - Sophomore
      - Junior
      - Senior
      - Super Senior
      - Graduate Student
  - title: "All Fall 2020 courses (technical + nontechnical)"
    type: "short"
    placeholder: "CS61A, EE16A, English R1B"
    required: True
  - title: "All Fall 2020 extracurricular commitments"
    type: "short"
    placeholder: "Insert x club, research, or job"
    required: True
  - title: "I am able to meet weekly on Sundays 4-6pm"
    description: "This is a hard requirement to join Berkeleytime. If you are not available you will not be considered for this team."
    type: "multiple_choice"
    placeholder: "Choose an option"
    required: True
    choices:
      - "Yes"
      - "No"
  - title: "Which positions are you applying for?"
    placeholder: "1st choice"
    type: "multiple_choice"
    required: True
    gap: False
    choices:
      - Frontend Engineer
      - Backend Engineer
      - iOS Engineer
      - Android Engineer
      - N/A
  - placeholder: "2nd choice"
    type: "multiple_choice"
    choices:
      - Frontend Engineer
      - Backend Engineer
      - iOS Engineer
      - Android Engineer
      - N/A
  - title: "Which teams are you applying for?"
    placeholder: "1st choice"
    type: "multiple_choice"
    required: True
    gap: False
    choices:
      - Berkeleytime
      - Beehive
      - Berkeley Mobile
      - API Team
      - N/A
  - placeholder: "2nd choice"
    type: "multiple_choice"
    gap: False
    choices:
      - Berkeleytime
      - Beehive
      - Berkeley Mobile
      - API Team
      - N/A
  - placeholder: "3rd choice"
    type: "multiple_choice"
    gap: False
    choices:
      - Berkeleytime
      - Beehive
      - Berkeley Mobile
      - API Team
      - N/A
  - placeholder: "4th choice"
    type: "multiple_choice"
    choices:
      - Berkeleytime
      - Beehive
      - Berkeley Mobile
      - API Team
      - N/A
  - title: "Resume"
    description: 
      "PDF Only. Please omit or hide your name and high school and name the pdf Engineering_Resume."
    placeholder: "Upload a File"
    type: "file"
    accept: ".pdf"
    required: True
  - title: "My name and high school is not visible on my resume, and the pdf is named Engineering_Resume."
    type: "multiple_select"
    required: True
    choices:
      - "Yes"
  - title: "GitHub Link"
    type: "short"
    placeholder: "github.com/..."
  - title: "Portfolio/Personal Website"
    type: "short"
    placeholder: "myportfolio.me/..."
  - title: "What is your biggest technical strength and how can it be used to improve an OCTO product?"
    description: "Max 100 words."
    type: "long"
    required: True
