info:
  unique_name: "TestSurvey0"
  public_name: "TestSurvey"
  description: "For Testing Use"
  googlesheet_link: "https://docs.google.com/spreadsheets/d/1WEy7XNrndAqOeQ6YHcQzUEuuqrp07xL-DpXf9Hs9m8A/edit#gid=0"
  drive_folder_name: "InitialTests"
sections:
  - "Test Section"
questions:
  - title: "Test Q1"
    section: "Test Section"
    type: "short"
  - title: "Test Q2"
    section: "Test Section"
    type: "short"
  - title: "Test Q3"
    section: "Test Section"
    type: "short"
  - title: "Test Q4"
    section: "Test Section"
    type: "short"
  - title: "Test Q5"
    section: "Test Section"
    type: "file"