# -*- coding: utf-8 -*-
"""Berkeleytime-SemanticSearchipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RgT99TQlAS_5u-Y42NiAGI9__lNuHXbF
"""
import json
import faiss
import numpy as np
from sentence_transformers import SentenceTransformer

import requests, json, faiss, numpy as np
from sentence_transformers import SentenceTransformer
from collections import defaultdict

url = "https://beta.berkeleytime.com/api/graphql"
coursesQuery = """
query Catalog($year: Int!, $semester: Semester!) {
  catalog(year: $year, semester: $semester) {
    courseNumber
    subject
    number
    course {
      title
      description
    }
  }
}
"""

resp = requests.post(url, json={"query": coursesQuery, "variables": {"year": 2026, "semester": "Spring"}})
resp.raise_for_status()
data = resp.json()
courses = data["data"]["catalog"] or []

# --- CONFIG: subjects to keep (tune this list as you like) ---
ALLOWED_SUBJECTS = {"COMPSCI", "EECS", "DATA", "INFO", "STAT", "COGSCI", "INDENG", "MATH"}

# --- Build texts correctly using the nested fields ---
course_texts = []
kept_idx = []  # map from embedding row -> original course index
for i, c in enumerate(courses):
    subj = (c.get("subject") or "").strip()
    if subj and ALLOWED_SUBJECTS and subj not in ALLOWED_SUBJECTS:
        continue
    num = c.get("number", "")
    title = ((c.get("course") or {}).get("title") or "").strip()
    desc = ((c.get("course") or {}).get("description") or "").strip()
    # Boost title by repeating it a bit; include subject+number explicitly
    text = f"SUBJECT: {subj} NUMBER: {num}\nTITLE: {title}\nDESCRIPTION: {desc}\n"
    course_texts.append(text)
    kept_idx.append(i)

# Guard in case filtering removed everything
if not course_texts:
    # fallback: no subject filter
    kept_idx = list(range(len(courses)))
    course_texts = []
    for i, c in enumerate(courses):
        subj = (c.get("subject") or "").strip()
        num = c.get("number", "")
        title = ((c.get("course") or {}).get("title") or "").strip()
        desc = ((c.get("course") or {}).get("description") or "").strip()
        text = f"SUBJECT: {subj} NUMBER: {num}\nTITLE: {title}\nDESCRIPTION: {desc}\n"
        course_texts.append(text)

# --- Embeddings + FAISS (cosine) ---
model = SentenceTransformer("all-MiniLM-L6-v2")
emb = np.asarray(model.encode(course_texts, convert_to_numpy=True), dtype="float32")
faiss.normalize_L2(emb)
index = faiss.IndexFlatIP(emb.shape[1])
index.add(emb)

# --- Lightweight keyword re-ranker to prefer obvious AI courses ---
AI_KEYWORDS = {"artificial intelligence", "ai", "machine learning", "ml", "deep learning", "neural", "nlp"}

def keyword_boost(text: str) -> int:
    t = text.lower()
    return sum(1 for k in AI_KEYWORDS if k in t)

def getCourses(query: str, topK: int = 5):
    q = np.asarray(model.encode([query], convert_to_numpy=True), dtype="float32")
    faiss.normalize_L2(q)
    sims, idxs = index.search(q, min(topK*5, len(emb)))  # overfetch then re-rank
    results = []
    for sim, local_idx in zip(sims[0], idxs[0]):
        original_i = kept_idx[local_idx]
        c = courses[original_i]
        subj = c.get("subject", "")
        num = c.get("courseNumber", "")
        title = ((c.get("course") or {}).get("title") or "")
        desc = ((c.get("course") or {}).get("description") or "")
        text = course_texts[local_idx]
        results.append({
            "subject": subj,
            "courseNumber": num,
            "title": title,
            "score": float(sim),
            "kw_boost": keyword_boost(title + " " + desc),
        })
    # re-rank: keyword boost first, then embedding score
    results.sort(key=lambda r: (r["kw_boost"], r["score"]), reverse=True)
    return results[:topK]

# Example
for r in getCourses("Artificial Intelligence", topK=5):
    print(f"{r['subject']} {r['courseNumber']} — {r['title']} (sim={r['score']:.3f}, kw+={r['kw_boost']})")

# Example
for r in getCourses("", topK=5):
    print(f"{r['subject']} {r['courseNumber']} — {r['title']} (sim={r['score']:.3f}, kw+={r['kw_boost']})")