# Generated by apps/backend/scripts/generate-operation-allowlist.mjs. Do not edit.

SEMANTIC_SEARCH_OPERATION_IDS = {
  "SemanticSearchCatalog": "141950a047d51952546116886516e63b945e7d3ddc8f89a7317f19501f2f9413",
  "SemanticSearchTerms": "383c19923625189d6af6177c3adb4ab4d2357bed1f24f838fb640a472b08565f"
}
