# Generated by apps/backend/scripts/generate-operation-allowlist.mjs. Do not edit.

SEMANTIC_SEARCH_OPERATION_IDS = {
  "SemanticSearchCatalog": "141950a047d51952546116886516e63b945e7d3ddc8f89a7317f19501f2f9413",
  "SemanticSearchTerms": "4bf7a28744fcfd8f32e8603110d32ad5bbc244166ef9f748c86815f066be29a0"
}
