# Generated by apps/backend/scripts/generate-operation-allowlist.mjs. Do not edit.

SEMANTIC_SEARCH_OPERATION_IDS = {
  "SemanticSearchCatalog": "7c938d0d2349effae7556315064213ebd7b7f27dda00ef5ccfb5a503df303f2a",
  "SemanticSearchTerms": "383c19923625189d6af6177c3adb4ab4d2357bed1f24f838fb640a472b08565f"
}
