apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infra/argocd/apps
    repoURL: https://github.com/asuc-octo/berkeleytime.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
