# This initializes Rook's Ceph cluster, an abstraction that can
# provide block storage file systems (rbd: RADOS Block Devices) or
# network file systems (CephFS) that k8s uses for dynamic persistent volumes
---
# https://stackoverflow.com/questions/51986300/kubernetes-default-qos-for-whole-namespace
# Kubernetes default QoS for whole namespace
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v15.2.8
  skipUpgradeChecks: true
  dataDirHostPath: /var/lib/rook
  mon:
    allowMultiplePerNode: false
    count: 1
  crashCollector:
    disable: true
  resources:
    # api:
    #   requests:
    #     cpu: "100m"
    #     memory: "250M"
    #   limits:
    #     cpu: "100m"
    #     memory: "250M"
    # mgr:
    #   requests:
    #     cpu: "100m"
    #     memory: "750M"
    #   limits:
    #     cpu: "100m"
    #     memory: "750M"
    # mon:
    #   requests:
    #     cpu: "200m"
    #     memory: "1000M"
    #   limits:
    #     cpu: "200m"
    #     memory: "1000M"
    # osd:
    #   requests:
    #     cpu: "200m"
    #     memory: "2G"
    #   limits:
    #     cpu: "200m"
    #     memory: "2G"
  storage:
    useAllNodes: true
    useAllDevices: true
    # deviceFilter: vd[b-z] # OCF: vdb, vdc / GCP: sdb, sdc
# ---
# kind: ConfigMap
# apiVersion: v1
# metadata:
#   name: rook-config-override
#   namespace: rook-ceph
# data:
#   config: |
#     [global]
#     osd_pool_default_size = 1
#     mon_warn_on_pool_no_redundancy = false
