"""List of exceptions generated by Catalog service."""

# Schedule


class ScheduleServiceException(Exception):
    """Generic Schedule Service Exception."""

    pass


class ScheduleResourceException(ScheduleServiceException):
    """Exception for invalid response from SIS Schedule endpoint."""

    pass


class ScheduleValidationException(ScheduleServiceException):
    """Exception for invalid SIS Schedule schema."""

    pass


class ScheduleMapperException(ScheduleServiceException):
    """Exception for logic issue while mapping to entity.Schedule."""

    pass


# Courses


class CourseServiceException(Exception):
    """Generic Course Service Exception."""

    pass


class SISCourseResourceException(CourseServiceException):
    """Exception for invalid response from SIS Course endpoint."""

    pass


class SISCourseResource404Exception(SISCourseResourceException):
    """Exception for 404 response from SIS Course endpoint."""

    pass