# Generated by Django 3.1.1 on 2020-10-24 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BerkeleytimeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=100)),
                ('email_class_update', models.BooleanField(default=False)),
                ('email_grade_update', models.BooleanField(default=False)),
                ('email_enrollment_opening', models.BooleanField(default=False)),
                ('email_berkeleytime_update', models.BooleanField(default=False)),
                ('saved_classes', models.ManyToManyField(to='catalog.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='berkeleytimeuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
