# Generated by Django 3.1.1 on 2020-10-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='semester',
            field=models.CharField(default='spring', max_length=50),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='year',
            field=models.CharField(default='2021', max_length=4),
        ),
    ]
