# "Kubernetes: The client source IP preservation dilemma"
# https://elsesiy.com/blog/kubernetes-client-source-ip-dilemma
# https://www.yellowduck.be/posts/k8s-getting-real-ip-digital-ocean/
kind: Service
apiVersion: v1
metadata:
  name: nlb-tcp
  namespace: ingress-nginx
spec:
  loadBalancerIP: ${DEVICE_IP}
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: bt-gitlab-ssh
      port: 2222
      targetPort: 2222
    - name: bt-psql-staging
      port: 5432
      targetPort: 5432
    - name: bt-redis-staging
      port: 6379
      targetPort: 6379
    - name: tcp
      port: 10001
      targetPort: 10001
