semesters:
    - "Spring 2017"
    - "Fall 2016"
    - "Spring 2016"
    - "Fall 2015"
    - "Spring 2015"
    - "Fall 2014"
    - "Spring 2014"
    - "Fall 2013"
    - "Spring 2013"

current_term_id: 2172

haas:
    arts_and_literature:
        name: "Haas Arts and Literature"
    biological_science:
        name: "Haas Biological Sciences"
    historical_studies:
        name: "Haas Historical Studies"
    international_studies:
        name: "Haas International Studies"
    philosophy_and_values:
        name: "Haas Philosophy and Values"
    physical_science:
        name: "Haas Physical Science"
    social_and_behavior_sciences:
        name: "Haas Social and Behavioral Sciences"
    abbreviations:
        - "UGBA"
        - "EWMBA"
        - "XMBA"
        - "MBA"
        - "PHDBA"

engineering:
    foreign_language:
        url: "http://guide.berkeley.edu/undergraduate/colleges-schools/engineering/approved-foreign-language-courses/"
        name: "Engineering Foreign Language"

    hss:
        name: "Humanities and Social Sciences"

    abbreviations:
        - "BIO ENG"
        - "CHM ENG"
        - "CIV ENG"
        - "DEV ENG"
        - "EECS"
        - "EL ENG"
        - "ENGIN"
        - "IND ENG"
        - "MAT SCI"
        - "MEC ENG"
        - "NSE"
        - "NUC ENG"

rc:
    url:
        "http://ls-advise.berkeley.edu/requirement/rccourses.html"

course_numbers:
    ls:
        sbs:
            ethnic_studies:
                - "10A"
                - "10AC"
                - "10B"
                - "11AC"
                - "20AC"
                - "21AC"
                - "30"
                - "39A"
                - "41AC"
                - "C73AC"
                - "100"
                - "101A"
                - "101B"
                - "103A"
                - "103B"
                - "103C"
                - "103D"
                - "103E"
                - "122AC"
                - "123"
                - "124"
                - "125AC"
                - "C126"
                - "128"
                - "130AC"
                - "131"
                - "132"
                - "133AC"
                - "135"
                - "136"
                - "141"
                - "142"
                - "143"
                - "144AC"
                - "145"
                - "146"
                - "147"
                - "148"
                - "149"
                - "150"
                - "150AC"
                - "159AC"
                - "C170"
                - "C173"
                - "181AC"
            ls:
                - "17"
                - "18"
                - "20C"
                - "23"
                - "C30U"
                - "C30V"
                - "C30W"
                - "C30Y"
                - "40AC"
                - "40B"
                - "70B"
                - "80A"
                - "C103"
                - "116"
                - "119AC"
                - "120"
                - "120C"
                - "122"
                - "126"
                - "127"
                - "140D"
                - "C140U"
                - "C140V"
                - "150A"
                - "C150T"
                - "160A"
                - "160C"
                - "C160V"
                - "170AC"
                - "C170AC"
                - "180A"
                - "180AC"
                - "180B"
                - "180C"
                - "C180T"
                - "C180U"
                - "C180V"
                - "C180W"
                - "C180X"
