# Default values
# https://github.com/istio/istio/blob/41b7d5b72f177303e98cb89dbc53ad8aada4adf6/manifests/charts/istio-control/istio-discovery/values.yaml
global:
  # hub: docker.io/istio
  # tag: 1.9.0 # https://hub.docker.com/r/istio/pilot/tags
  istioNamespace: istio
  proxy:
    autoInject: disabled
    excludeIPRanges: 10.96.0.0/12 # inter-cluster traffic breaks without this, kubectl describe pod kube-apiserver -n kube-system | grep 'service-cluster-ip-range'
meshConfig:
  rootNamespace: istio
sidecarInjectorWebhook:
  # You can use the field called alwaysInjectSelector and neverInjectSelector which will always inject the sidecar or
  # always skip the injection on pods that match that label selector, regardless of the global policy.
  # See https://istio.io/docs/setup/kubernetes/additional-setup/sidecar-injection/#more-control-adding-exceptions
  alwaysInjectSelector:
    - matchExpressions:
        - key: sidecar.istio.io/inject
          operator: In
          values:
            - "true"
