global:
  hub: docker.io/istio
  tag: 1.9.0 # https://hub.docker.com/r/istio/pilot/tags
  istioNamespace: istio
  proxy:
    autoInject: disabled
    excludeIPRanges: 10.96.0.0/12 # inter-cluster traffic breaks without this, kubectl describe pod kube-apiserver -n kube-system | grep 'service-cluster-ip-range'
meshConfig:
  rootNamespace: istio
