# https://github.com/elastic/helm-charts/blob/7.9/metricbeat/values.yaml
daemonset:
  # For environment variables in bt-metricbeat-metricbeat-kv6mg
  extraEnvs:
    - name: ELASTICSEARCH_HOSTS
      value: http://bt-elasticsearch:9200
    # - name: ELASTICSEARCH_USERNAME
    #   valueFrom:
    #     secretKeyRef:
    #       name: general-secrets
    #       key: USERNAME_ELASTICSEARCH_USER_ELASTIC
    # - name: ELASTICSEARCH_PASSWORD
    #   valueFrom:
    #     secretKeyRef:
    #       name: general-secrets
    #       key: PASSWORD_ELASTICSEARCH_USER_ELASTIC
  metricbeatConfig:
    metricbeat.yml: |
      output.elasticsearch:
        hosts: '${ELASTICSEARCH_HOSTS}'
        # username: '${ELASTICSEARCH_USERNAME}'
        # password: '${ELASTICSEARCH_PASSWORD}'
      hosts: ["${ELASTICSEARCH_HOSTS}"]
      setup:
        kibana:
          host: bt-kibana-kibana:5601
          path: /kibana
        ilm:
          enabled: true
        dashboards:
          enabled: true
          retry:
            enabled: true
      metricbeat.modules:
        - module: kubernetes
          metricsets:
            - container
            - node
            - pod
            - system
            - volume
          period: 10s
          host: "${NODE_NAME}"
          hosts: ["https://${NODE_NAME}:10250"]
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          ssl.verification_mode: "none"
          # If using Red Hat OpenShift remove ssl.verification_mode entry and
          # uncomment these settings:
          #ssl.certificate_authorities:
            #- /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
          processors:
          - add_kubernetes_metadata: ~
        - module: kubernetes
          enabled: true
          metricsets:
            - event
        - module: system
          period: 10s
          metricsets:
            - cpu
            - load
            - memory
            - network
            - process
            - process_summary
          processes: ['.*']
          process.include_top_n:
            by_cpu: 5
            by_memory: 5
        - module: system
          period: 1m
          metricsets:
            - filesystem
            - fsstat
          processors:
          - drop_event.when.regexp:
              system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
      kube-state-metrics-metricbeat.yml: |
          metricbeat.modules:
          - module: kubernetes
            enabled: true
            metricsets:
              - state_node
              - state_deployment
              - state_replicaset
              - state_pod
              - state_container
            period: 10s
            hosts: ["${KUBE_STATE_METRICS_HOSTS}"]
          output.elasticsearch:
            # username: '${ELASTICSEARCH_USERNAME}'
            # password: '${ELASTICSEARCH_PASSWORD}'
            hosts: ["${ELASTICSEARCH_HOSTS}"]
replicas: 1
deployment:
  extraEnvs:
    - name: ELASTICSEARCH_HOSTS
      value: http://bt-elasticsearch:9200
    # - name: ELASTICSEARCH_USERNAME
    #   valueFrom:
    #     secretKeyRef:
    #       name: general-secrets
    #       key: USERNAME_ELASTICSEARCH_USER_ELASTIC
    # - name: ELASTICSEARCH_PASSWORD
    #   valueFrom:
    #     secretKeyRef:
    #       name: general-secrets
    #       key: PASSWORD_ELASTICSEARCH_USER_ELASTIC
# resources:
#   requests:
#     cpu: "100m" # Default: 100m
#     memory: "200Mi" # Default: 100Mi
#   limits:
#     cpu: "100m" # Default: 1000m
#     memory: "200Mi" # Default: 200Mi
