# https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/values.yaml
# Secret formats: https://github.com/bitnami/charts/blob/f8d79eacbefae13f60e93fe7fe85741c03fb9d69/bitnami/postgresql-ha/templates/pgpool/deployment.yaml
global:
  postgresql:
    username: bt
    database: bt
    repmgrUsername: repmgr
    repmgrDatabase: repmgr
    existingSecret: bt-psql-${CI_ENVIRONMENT_NAME}
  pgpool:
    adminUsername: admin
    existingSecret: bt-psql-${CI_ENVIRONMENT_NAME}
postgresqlImage:
  registry: docker.io
  repository: bitnami/postgresql-repmgr
  tag: 12
  pullPolicy: IfNotPresent
  debug: false
pgpoolImage:
  registry: docker.io
  repository: bitnami/pgpool
  tag: 4.1.4-debian-10-r24
  pullPolicy: IfNotPresent
  debug: false
volumePermissionsImage:
  registry: docker.io
  repository: bitnami/minideb
  tag: buster
  pullPolicy: Always
metricsImage:
  registry: docker.io
  repository: bitnami/postgres-exporter
  tag: 0.8.0-debian-10-r242
  pullPolicy: IfNotPresent
  debug: false
postgresql:
  replicaCount: 1
pgpool:
  replicaCount: 1
persistence:
  enabled: true
  mountPath: /bitnami/postgresql
  accessModes:
    - ReadWriteOnce
  size: 5Gi
service:
  type: ClusterIP
  port: 5432
networkPolicy:
  enabled: false
  allowExternal: true
