# https://github.com/bitnami/charts/blob/4aad73ac532eb282e2c68162b475b0a1ae264e30/bitnami/redis/values.yaml
usePassword: true
existingSecret: general-secrets
existingSecretPasswordKey: PASSWORD_REDIS_PASSWORD
persistence:
  enabled: false
  path: /data
  subPath: ""
  accessModes:
    - ReadWriteOnce
  size: 100M
networkPolicy:
  enabled: true
  allowExternal: true

