# https://github.com/bitnami/charts/blob/4aad73ac532eb282e2c68162b475b0a1ae264e30/bitnami/redis/values.yaml
usePassword: true
password: Gobears123
persistence:
  enabled: true
  path: /data
  subPath: ""
  accessModes:
    - ReadWriteOnce
  size: 100M
networkPolicy:
  enabled: true
  allowExternal: true
