# from: service

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: {{ .Chart.Name }}-frontend-deployment
  name: {{ .Chart.Name }}-frontend-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      component: {{ .Chart.Name }}-frontend-deployment
  template:
    metadata:
      labels:
        component: {{ .Chart.Name }}-frontend-deployment
    spec:
      containers:
        - name: {{ .Chart.Name }}-frontend-container
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          command: ["npm", "run", "prod"]
          ports:
            - containerPort: {{ .Values.frontend.port }}
---
# to: deployment
# from: ingress

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-frontend-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    component: {{ .Chart.Name }}-frontend-deployment
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
---
# to: service
# from: ingress-controller

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-frontend-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{/* TODO: add annotations */}}
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Chart.Name }}-frontend-service
              port:
                number: {{ .Values.frontend.service.port }}
