apiVersion: apps/v1
kind: Deployment
metadata:
  name: berkeleytime-prod
  namespace: berkeleytime
spec:
  selector:
    matchLabels:
      appName: berkeleytime-prod
  replicas: 4
  template:
    metadata:
      labels:
        appName: berkeleytime-prod
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      containers:
      - name: berkeleytime-prod
        imagePullPolicy: Always
        image: index.docker.io/berkeleytime/berkeleytime
        command: ["python", "manage.py", "runserver"]
        env:
        - name: GET_HOSTS_FROM
          value: dns
        envFrom:
        - configMapRef:
            name: django-configs
        - secretRef:
            name: aws
        - secretRef:
            name: google
        - secretRef:
            name: sis
        - secretRef: 
            name: sendgrid
        - secretRef:
            name: sentrydsn
        ports:
        - containerPort: 5000
