apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bt-app.agFrontendName" . }}
  labels:
    {{- include "bt-app.agFrontendLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.agFrontend.replicas }}
  selector:
    matchLabels:
      {{- include "bt-app.agFrontendLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bt-app.agFrontendLabels" . | nindent 8 }}
    spec:
      containers:
        - name: ag-frontend
          image: {{ printf "%s/%s:%s" .Values.agFrontend.image.registry .Values.agFrontend.image.repository ( toString .Values.agFrontend.image.tag ) }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.agFrontend.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.agFrontend.port }}
            initialDelaySeconds: 5
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "bt-app.agFrontendName" . }}-svc
  labels:
    {{- include "bt-app.agFrontendLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "bt-app.agFrontendLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.agFrontend.port }}
