apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bt-app.backendName" . }}
  labels:
    {{- include "bt-app.backendLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "bt-app.backendLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bt-app.backendLabels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: {{ printf "%s/%s:%s" .Values.backend.image.registry .Values.backend.image.repository .Values.backend.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: {{ include "bt-app.backendName" . }}-env
            - secretRef:
                name: {{ include "bt-app.backendName" . }}-secret
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 15
            periodSeconds: 3

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bt-app.backendName" . }}-env
  labels:
    {{- include "bt-app.backendLabels" . | nindent 4 }}
data:
  PORT: {{ .Values.backend.port | quote }}
  URL: "http://localhost:5001"
  BACKEND_PATH: {{ .Values.backend.path }}
  GRAPHQL_PATH: "/graphql"
  NODE_ENV: {{ .Values.nodeEnv }}
  MONGODB_URI: {{ .Values.mongoUri }}
  REDIS_URI: {{ .Values.redisUri }}

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "bt-app.backendName" .}}-secret
  labels:
    {{- include "bt-app.backendLabels" . | nindent 4 }}
spec:
  encryptedData:
    GOOGLE_CLIENT_ID: AgBdqpE1M9azG5oKaCfYqwa2vdaH5LXYp78eizNm492fzFGqxBgS1Ugty0MfJzg2A1fvMo+vwM693Cn8kd1a4f08TEqe86qqjta+OfjZ23nQYjG7wi8OMla3lqCFk1sHknC20aOTapgRr0oqbo5VNVkz9FVeEAy56fd0rCsAitlvW8NzyhjKBm2jP4BViO+B4Tror0z1i9t7gkBmKnNfIiDqoLIjq+avO+AyplV7K5HQ5NCWHPhGqHcH2/AaI49+55Hbsn+rw23O4NHguE5DOhACVXrjQ3dNaoJ2i7JK4V21b011Dlfh7PQ0cyoDSnsriHJY93UmXDBEpED7GlM89zctiS1+OVu72H31QTvsmHRP6bfcmpnjs8ZNPFWK0J7moQ+eM7gTkcFHOQD7nKWNNrLx8jVp6+fMZg8x5UIs9UFUWmN/Xmn+Oq0iNouMKiT/+8Rpz6MbOIxukFhVHbtPtc3hIP+BrwMimJ519+tlo4bKkCyMaIJEIMfyR+Kl78g7/lC+i9k+ArlhfukxM7FEtb6LIygSmq69PM1zITRuGWjm2QJ77xotfiOYL38ssic87UDBgs0icG7jxwICVZKVjzr4glzlQ6qXDPWM+PhWeSlsl7ddgWfL5mh1hSU+iiBxYGV9Nc9+UYKlB3CsLsaeshOgXgWIbNxk2/d1QIpQ5yzWYvJfFEhSgPz5p+Xb0VetI4wHn78DZp30humpoLL59qOwtKVK0aKexxG+dU/3NAdHM/3OI8O/M6HZ+6EIWBHgdJgw4K/V1pypgZdNItagAf0SKiA9uDs4bx8=
    GOOGLE_CLIENT_SECRET: AgA9V8ZIydND5syRP0I6+Mt+IsEzbulZezme3saqWwL8kef6/Yz+LUF0XmaU/OediDQxxc6edavvmEgXCwyTj6G3ZztHveHCei7RbyhyrdXduM+Hm1AwrkGqn496/0yRaHENOXe9jz+rky4/0cLxC45t//1DxZaDrrWv7RpHrbG9Nkxq1Vc6Nk4BxWVbfYEldTwEHmaGEWdETU1q/P3RQJYt5UekXO62Di2/AuquvIp+xpGnQ8CMw+9tkJNChCpGblcftBJ7kCxfDP//gVBnt4heUh8uHioBeUexyuX9Wp3Um6Naz04xRT3VZ03hAvLHmtsj88xX4dmBq5+p5U9ebCiO85d8xKvjqtBtt6NJoCChjWaUic6AXEg0KpwoFcPCVU8GBSJFPOVW3R4l7HOorw4p7iO/kr+ATiL1WF4GZDD0yRJGAonz0NF3/FdpprUELco47+Gqa6nDJD5QgAYXubk/Jbjaanun83smIcmOT9FBDJzFvjlfgUHF0Gpq4hKP1PUC+E0ZmP64ElCVnanzrLMr9/pGhW4y8qfA19ANHsnZkPg/Q/08tgULI8JMxC1pyAtPwcqNJbMl0tWJwx5jhdEljgssqx6S1lqfTIZAoT2a188tdO3shjRzytMYZAdVTtbJCoLslBnrniliD9OKVR8IsHzaEpN63oiSGOrDgwlNYidPyEdgChJBi+VfaLlGWnTn+zIA0cu1ChJvBath4rAXIxOPc3Y8J2E=
    SESSION_SECRET: AgAhp8ldhpzhEkR1F29A14l6f35da0F4AYIY9AYwcIbqgifH8uK6Yd61YKGfjpdFgD9+Gne5O+qoAb7KBv4IRPdlKwfbQDJOr04Nz1YdSIg/qCMXvKemyAXS726O+Myt011rI/PRdJi1eYuloU+gdfbWxfMWwji9OjzrscczPcXucvZzIrOcJrRFJYMSrkZln76wL8bgClLDmBDCYBr5i7Dx1E8cfkJE1bqvl9PN6x+nnQWjSspepFBAx7j7tQn48Up8yfNaxC9ynL20d+G1qaVpokcDbCM1hSTA+WhUH1w9Q0Hw8F9hLiGhxwx+q06tMRqTIUtRnQ2GtobpKImQqBlKxJGv3tMBubxpmttmlE+ns7fv5H7P9kG8MvmWh2zHHEcuDQ5sIRtVbBBu9aVZhcPeDYAqSlK8v94bN4Z2ULR3A71HuDd/+0CgvbUw6v7Fw+A6rzN6lIHVIOD4AICkldGvHPmo/hXlQC1h7YAzB4c82SKPsHcWvl6ALZW842hEA1UH2MGRtoKNJMMMte3qFEMHheK5w7uzKYN+cUXZ8nYVfEyvuhuu6xLNlf+DVcZvL44XlqPPu54J98W8gN6txstCZJF5P+BtRPYbVcGLv+a76YGlpiwU+i9ZHVRe2EN4lQew7TsUioo91li9zNNbwJPz22K7UsJVMp8OhtzzUmiS6VWNRKLkqXptM5GT83CVq3isZ1idjNhe5kxb
  template:
    metadata:
      name: {{ include "bt-app.backendName" .}}-secret
      labels:
        {{- include "bt-app.backendLabels" . | nindent 4 }}
    type: Opaque

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "bt-app.backendName" . }}-svc
  labels:
    {{- include "bt-app.backendLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "bt-app.backendLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.backend.port }}
