apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bt-app.backendName" . }}
  labels:
    {{- include "bt-app.backendLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "bt-app.backendLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bt-app.backendLabels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: {{ printf "%s/%s:%s" .Values.backend.image.registry .Values.backend.image.repository ( toString .Values.backend.image.tag ) }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backend.port }}
            - containerPort: {{ .Values.backend.cacheWarmingPort }}
          envFrom:
            - configMapRef:
                name: {{ include "bt-app.backendName" . }}-env
            - secretRef:
                name: {{ include "bt-app.backendName" . }}-secret
          resources:
            requests:
              ephemeral-storage: "500Mi"
            limits:
              ephemeral-storage: "2Gi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 5
            periodSeconds: 3

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bt-app.backendName" . }}-env
  labels:
    {{- include "bt-app.backendLabels" . | nindent 4 }}
data:
  PORT: {{ .Values.backend.port | quote }}
  CACHE_WARMING_PORT: {{ .Values.backend.cacheWarmingPort | quote }}
  URL: "http://localhost:5001"
  BACKEND_PATH: {{ .Values.backend.path }}
  BACKEND_PUBLIC_URL: {{ printf "https://%s%s" .Values.host .Values.backend.path | quote }}
  GRAPHQL_PATH: "/graphql"
  NODE_ENV: {{ .Values.nodeEnv }}
  MONGODB_URI: {{ .Values.mongoUri }}
  REDIS_URI: {{ .Values.redisUri }}
  SIS_CLASS_APP_ID: "_" # TODO: remove from backend
  SIS_CLASS_APP_KEY: "_"
  SIS_COURSE_APP_ID: "_"
  SIS_COURSE_APP_KEY: "_"
  SIS_TERM_APP_ID: "_"
  SIS_TERM_APP_KEY: "_"

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: {{ include "bt-app.backendName" .}}-secret
  labels:
    {{- include "bt-app.backendLabels" . | nindent 4 }}
spec:
  encryptedData:
    CLOUDFLARE_API_TOKEN: AgCeZFQuDk9GyOK4IIf2J/bBQcZaouS1i5noolYEaP2E5A5aHoysFJTtGrEcL3mduzpnQ1Cg6bxPspQxFe4rxZvax7t2BBz+TaEkKOEhB1MerFN2kLUZzugKiLqPkXajJ7K9gaSY0WC+4k7VE19ayObr/Pe49zrwDm6t22LlawZCPEhpKqdC2uK7vfXz5tdA9459byKnvln7b8o76c7yCSD7k5v1cOZm0VqckfXGNg9A0wSMZDJhwNtmOnMOzN0Sswp81zXF77dzmVGH6J9MlijfJ4hbukYknTDoddDz/TfWc+ZDAAsC0hXqEoIcw1z8FYWFzlbbFpdkDm+0Ccp4pMkU7H6JZoNN8GVvb7Al5VFMTGNmWWQvzT8JbIW5T5XNCACvH5xT0zdeWrM43OXisd+j9g5op6dYI2GKAENovq7uo/tswaLocc5YmXTEXmE9Y4mDbLJDENjXdEWfi1WQb4MtJmzN8W1wn4Y9gFGZFP0HDXMrKcABFmcQxFIwubs8lq/eH/lGpwY27pB5PCybQHlyTe8yVLZYCsFhdTSCdLKN+P2ERz41tYql4C+pNyhckch0hteELQHbtKH3rBVqN3F4GIrbIWYGFH2NeClcTCjfiDpVtIlvwfREFWiUDNCGZUJSekYx/KeidZIZc6WiSV3p3F/lUApu7ABaZU8FBvuhrlTSGUcnulhjJuwFBU+P5cZxPJXyj5JCnRbKRxYA8+dJFQdB6MO7gItmubuN7+ahzMirjUbHB0pp
    CLOUDFLARE_ZONE_ID: AgBUJI/UjdVN78mCLO5+eZ3GNN950NvGvW4EydhqBH9gEHd4BI6SQpvgVaRDk+Ym5ETpik+IVwxZse3oqZF8VVQHJ6gkUnoxcyrwLPJN0Selkm1foySxbq8H4HbvHxY26t+RDUfTmYrhPZgaJvdL1Vj/v610737No6ognUi3ycqFkDSAWSktj+sFJRT7gz55QrKO0IW0nvy/ZILL6cBA+Oeslv0m6a4K1s3zKvZ9qfYkG5qKu9NEbrWBGU90TOWTAbHwY08+EicVT/Zk1dH6CCKw5zr04uunTChvLQUrflg1NQOfHNt/33McqeMMJ2FvPLbrA25n20VDomZlMw0p54H3FP4joAbuQDUOdNRcuDzQ5He8GEvcO9gTHMrv3qiJDvrAhQ0sr0Tduqxikhm+hZ7+XwIn1d4M3zjP9yAMV7/fpP5R71tN2pZhAnfj8xl2pbnQFutvRft1WWYY79Hlab0+bsp5TL0xxe+5YN/OW8H9w6Pg+rw+NuKiJn87bxGMjGukpUYvTu2neH8wbdO47szB+uuHA8Gvkys10gkIcCRZoJyDB/L74fMyo6gpnwhBSooJhmg5NLXGk0G8pR/TIKzbGVQfcYANvIuY82fH2hyWqyhDXhvK9MeweXVF/kKzeDH85qQbUHpR9whDorjXyiT3zqNF3AgWhwoM/3V5REP1ulbbDHWrYwLwFeqQ6HTtQ/5ITHVSFdT9UVzFk6q/Aq7rdboPo1U+UP6chAjvEheOtg==
    GOOGLE_CLIENT_ID: AgAQKa29ZFaq30Ue5nlPlzYhdZacU5oEmMdfAxgC4ZpDDKTlO5a4P4Pl1W8S1V9yXylQBRvhT80i+eszoOGR9J3dnhRK9c51SRZoAEaoAqaxWWwNANSSbT2jQ8rJ6A37dDfKGCNf2ud+vK8oxQsNb62PKTXmz8rE2iDJ3DIQ/iiVzwV6w76MVZy8IeiGt8DKfdUtx3bJRVVUrciCDnT/YYgTHRTK6fwX9RRTMoftyp2/x/Ta/cvvGC94F4vs+lh5DBshPkH2t/mF0rVIY8axNAywKmL1jfdtKO3UQHK4mZTC5m0/zYCDH+a3ZKJNC1IEdDz6rcWE4rfTazEXTdD3AiBfF7KhREDWyrtrJ182yaJMZCKeGDDOln0MPlu9j8SP8KYpqkWOPPo/3E5N/ose0JESWQqHCKfzb3plBU5CmJSw+IFWShQoaJ9hBpErZ25CR/3dbBlAGIAFfnrFu0Em8CkdfYzKxBGtUv7BygsHmHASLFnH6TXzPYT38fUz0JFncvTPXQjK/csM6UM8nYtyGn6yBwk4V4+sF4jGYrUjY5mxEyxAzXQwP+iAfBSaf/SI8HH1osnqM0eLr3DJCo5dp5QahPK8UoKA1Cnbq/e/ESoEGGUI69D5bsZOrct96BGnSVu9K3B26i8Sr3xlvfN8iYkZI9U/M/i+0BsYBtF9ftHSbczQe1n7lVNAzKKSUXMMMjWqMqBAfS7mAD8BRWfuEPAV7Y+NJTgR7o58HEkoGoEYJ+mtYoAyIHHN8b2quSonKfe19F5wGX2wW8t8qTAoRWbg/T0zhP8yM7c=
    GOOGLE_CLIENT_SECRET: AgArtbnvCf8XNdzWG7Y/R0HYDNfTgPWCzr9jNQ3+mDnTC0thGZbypBn4tlJBge3nvqrjIZAkoSchrJle85NaKRR8U77RxEy+os/6jJdyT9vAEKJj20O4aB7igjpmkgvIZhZNzaHOHLiQv2Xw0wa9dghqjTcFFoUwghrt6g/8m/8iGVQ5GCyGalQPiAI3dwIelDpbr4JcPBVSc6e0XNMI35JrOB7ouBlgZCml/Q2PQMKn5OwgHCxjl4jh8soGmlM+g2lYwCKPtghSaJnPWqpFJfF8V858a1D41L+LNXCIUo4g/jvVe5TJna5s5Z5lemUHy8KAqwAGls1IUgag8Ywy0VbFA/LHqTTJdHN0pep3rx2oGaz71opkYo87pHxRwC/F7RA3llpmybbslFFwfNdmUWJCBnmg2pcCUbQ3G1iBE+pN/HPp/ErjqSg47SoMvUXZhvEuYNsINah2X5Vg7BXOeYjI+uGvg2AhKASg+tHk4p3OsaWen8tIjlW5Qax3P9FeLfxIJn9EUEZsSZ0FEXJSX/cjVYrWEf/DiKF8pft2ROeY+JfYyyCcOihp4w4PcLN2uQ7GztedaJZFokhwQR1LJ17fPk4xJZzMvWiqbEbQ/EaMLe03tzpak8ThyLAZ6FlJ9OvGZ992sddf1qExt1PGy2Hu1jkGFopevPKLc8wYZISvNOH6njjXRAArPcDzfeivJeHzEOCGTaZcIReofNkHorQrssiULSQDY7JdfAYfHYBZ7XszWA==
    S3_ACCESS_KEY_ID: AgAELVtkMZ8Yle7j/9TRg9msc/S1yk/2CF3Qu5KZ04Arl/tlUmhaEtiU4Qrw7TgOH8cvggX442l5DN8Cri8E4zAJvShvprS1EuXWvvmay8O+Bcg6MWrJA+BtRwm0M3Qx1jFX1ed9BkhoRwYNeLMDltPvvX97lFNUKyK9dM1h1ibimVlN8Dy8ZjrtIq9CbzY9N+VRiaNzwDPLbTg6KE9x07wWbTdnFCpLlSKSapwwt6oFW6ntclNTzWuG0jJFvYyyQeRs6+ZD2/DbVGIueERjCNQAK/Is8rjN/8SYFqHbC3BuAZGMBbr8A4pSrjeE2SfPvQ2oYhW+VqJKu7/a4I3XLjHCz1iLBZkdy0z7O9XsrdKJQW2wuAZ4XcOl3qsj5e9sb5172RTKhyx5cc9rnFfTMOVnSu1YMrafVVNx50UvTklWoMhBRf0VE3gdWsWO3pslnZg3s9O7XhD328o8nO05rIKw6M1EJWr8BkL7qeJHW8SuB5E36/AVQ54KEUjmFBP8k3JCaFTJ9LbamiUMZw+oKSu9BSxH3Pn+A9k/Gt8BfNrBMdYXvYM2y0GVV7QNFI7iJPiI7/50jXf0ehl+UqnaezUbjvchmLYfLln32QV2VaO5HrPMdXGRjzEUfdKOQOzBYvIMMjFuY2hNQXMOV2J/8afFVUngz6yJ6pr5JfekBBc6Q3qF7uDQ7NphwDWvkX8CWOBwZlbrphlGJR0ciCb/vVpS84DfG/Hzf50houvwUZ9okQ==
    S3_ENDPOINT: AgA4XwmvSPSZo7nYBZIbJymmzw3aJMApnczPkkBvKXnhZxzdBPLffg4DTW3IneZuVtNAFj6cRsMZqO5pzNjfl6i62+ZbFkNgze/MxXNRT4qadOuKXzbn+0qzLRjtbMCcAMVMXRlk+7MvzQ0ftySX3/PZ8Rpzr4eOxs0b6GG5hWMdeGlW9xGBXgkQ6dA2Tj79cUy1wg+Pj2pCjcZ97gQzL2CHQ6SibRPWWWFCnXTRqfIGN6C+9au0moutEWkLwqQPayn86WsC9+GFbMtPEr4xzRQKIP+uqiN2oDXPFe7U++3lp4ifWFTE203ACJGgxTyvO6ElVayYoqqSxKXkQHyRGlE7fGXpNUrDUfs8fHz6NmhOJUgaAc+9kQpbrheW8h3248qgb42PhvNd/r/HlLotueQflt0uJm79GVsfuW5EUcTVDGWIu73e7J2sidTrDAF6T9OjHDj0i/f7sU9SnjtKbJFje6lHx9m+zKswZQjk+lUOitCfgZ7EpMrXKfAcmXbWejPVPOO0AOERdx9kMDjetT7ybpePY0AnCQLHSEQCZRG4Vvst/MnCaCyMWPwHOJqH0LFBT6uCY3jicKo3iXtZ401wtNiWKWUr8oL8RlGgsVrDR+ejvdK/MpW1Lbj8PtGUCgdLTfkixEuHm7WQwD5VUR6KpDEr7UQRbNSr7gXLQxDb8kwVp4gH7Y4LyQuwMQqe9Nwnyh0/JTzoG8ySIVv8efNDKAAMltXxrfQMQV//PZeoZH7LMdX0EC35fkesLOJij+65gCtPbiFTS+ouBWPzJm21jQ==
    S3_IMAGES_ACCESS_URL: AgBzRIuw95o2UX/KBd+Cf26QT/avh2NJG2kRHvpWAktzl0tnG99j+9pPkbGcY1k4qlScBQcK0St7QqdeSSrakK2MnCL4p2/0T5yJ/mbIQ1c0U0Id3S7qaHfDsxLdGM48mXVdxvbIkUIxamD7DInbi1hW3iLvh3PZwu4MWv9KiUr5OtZOIl1OFFF5sZcrsoRBAJy5QNr3FPUurihrZZGfZBcyDOF+3Eq3SiyaYnDgd17EigoweEbHMxP43KcJ/oYzOs6qQsJ3yTWg8mDOF8RSS29bOJ0RXeqvbYY9QuZaXT52KrETyMwqwOFb8h7Zjww8mTjUlwizLUKZcY2ZLwcmJS8/IIfWTQuSKv5xT4rQZ4zymjKp5Zkhi/niznNDuS2POFQaU2lnMFsFr4kpSszglA7/qIex9VU9chDG9Yhek2YorUYj0bMPa4XkNVIEaxO5Tc1nXT7wymOuo4p+NV8QAOLEwaXnptGhnRrB22aO1cRz/6s+4sjuQIODU7i0w4vSCf4GzT/dSpzQ6IwhpFnWK47DFnei+nJyJPs7mtUyjK467taDI6y8OdtmvgSF8bIqnDeDFTumIfOUe1j7KoorHsKZVWTVtoFOn8eJjiOAly1zMXbVgVG9kCMIXeZbRZsZV1xdpVmtB4T2biKX1qhWLKiu+Cr30H99857D6SPeq9N+vMsPxLmmlHL6DRkOznIKGPBdECYtTY4wz2LsM1hmRz6M8NF3o7cj7XxGy8HxZz4+
    S3_SECRET_ACCESS_KEY: AgARZc+zIoAnq/yTekaiNxwD3+txdCASfUNrAMp69Glsk7ibX+S9j2s9Y7+uq+jvDf8bKfbAI0hTtbZoh9zG9hI711mckiJbl+7nYuQfcqLKIHG8XEeB+yaGGL6F/opX8Wo2HxwZfFliZqfLmgKf6xP+DXu0iHbf3JQLo/Funk3e8RComsFxC2u8ejeALve0LSz8v6u14PfcbvZThSewf0UhhCROgnIH9z7xZzAskS9VZWLpcrTfjo5jXSU8WjVEWR32ebYcs4Y2+97AuDo5ZIbGSdF25IXK8moX+6RGym0vyhf0YAeLoC+PTxN5jGZ53bxEYWOQORKBPbqdrrHHNMQhY9TsJ+4UZGSE/QXASCzLzxpNGTIv8Xupn3TUXru/5+3QllZU6Qf7YCRyjOB8xera0MCSdDtm/8EIhH7uVvFq3uG1taMrqPk4W7Y5bMwfLn/JzxYcmcff+sPRCVF/sw806m/HlDRIAJk2ahR/FAftGzBnAoEgla1vL0qWKSSUPvvSwU9hC+aRFTDn/FP9gzgPoc5aMWqqI1iRyXox6qdsbH3o+pF1AHH41UWyZfcVmMYy/FGvzO/CLMykvVbHHLxCHeAH+AzXZ76dq736fqrSGjA5dre7cNhf3aKDjPdwu3tMUaRbnCWAV0heCcM4wlgiJ9vtzGIw4gNnZ1R6IrL4dwYwZv0168MC2X1uifYQfKhW+pqXWIoB0zQozsEwCY0CFse2mjYCPXu2qBY96YHWBIts8YlL+NwMwRy3/RZIEGjbN09UqnWGHBI1+GVruzWK
    SESSION_SECRET: AgAKDJIrkPJoiUgA/aWD7alXdTioGCkTBA4/lufNvw0b3q5C8iWTXx+IUNS7iwFVW7WSQ6oNfBn+vTQYVt1E9b9ZQFnYhZ2hMnJO8H3HgwhZR4WrHMSyBuPRh+/Qd0MLXSdkvLYCLhj6lkYfaSxB7/E5YjTVaM1kpkiWKmv5CIFYvzHn8K4acWaD4JzBd/k0JcYyBoma//ghFjYP5p/8fRVd1jVegWP0BCEG5gMlK7hZTeWZ8CkufEGrxkY3GSMlEjVCNeAG+E2yPlGWHz/5mFsmQ5guFQgVBSmeF/mm9D1R0Ez8lrAih3IsjHDIcpmxIz1XgZXwktpQDgJK4PKDN5zmSYTQEYY569o4bX/aQ2C4Zs/oIbr5W3nJsG++fMgiFB7bvoxE8q8ZJs1GdKvQhi1w3zLT/dTP02UoLsFij/jZSO2JiXf5WIopjRJJXkwg3SB3Eny2oV3LFyBfMZsHlj2p27IuQ7y9NA+RXb79wXt+1kUZpl8ktNgaRqhm6qJihj2W7k5zQ0hTKd3/1E+BBEUh7wvJLWxADo/vd+KfDSa9vdBx8EX/XBpbFuFpwnUdxvsfEfASe2MEkA4whwYlxFsgaTdHEz3OBuokonmGxAvDCZclMz5VMRdFs7B4LHgv3dDkn6TK9bB08LSUl1spMmpdlPYIvE4K5gclv3k4vKW3Kee7l/Zj0Mtc21oAyXlUni99w/bkGJ+iC5H+eazJpqzCu72loeIi8e8OVYXdw1P606hK/ZBA4B1cU8Bx+n6tg7jxFr3j32GYTD8ANaWqt6QT
    CLOUDFLARE_ACCESS_API_TOKEN: AgBcbXLkXiK5xrK2/8edRXhh0Dn1pKkdX+qAM8GpNibPwqoAGaBIfyEYd65nNmLY7IdwT4uWguiqWJjBDNST4YpkCQ+QWOOvZAu/HqTMqZ4dMuRovB8knMB68rovySS5ddVX/rpIMG7INIE7ctzUcax+gxjo8Mv76tXi/VYg1Y+uPQ+st2zuCZeZ2ugeXINaPZDmI9K2yL6EbsQU8ZkggvfZTmVSZbhJqowOCFN9gAJXT4q6wmAniI1HYXibTru0XN94+p9mfMVuWOaWezKRPAHOSsOmnoakKB5hihCopxZTTP/707W2EATAZRrTpdkJ0LJDCUQK4CDGvdw7vEpHVVXwmbtukSg6qZfYJ9zWe5EV1uxyEsYTojwPuVErV24MShlN2j0uSaUW0ELEbjfQX4TvKixwk2hbV27Sim92bGGqwgTGWG2TxqhvyBoLRF/2kXruOwmPBbUHkBnUhtKFYuvJDhwiNPkvwrVDU2PcUYLBXCByHwTuOVxfVTeOAMUmcC3OEDv0C0N5VPYnyCnZaie9yyZXF5xF1tSEkxS8COyVcKY20okHe3zcEA6GqN12mtYIwZRz7kvo6AfEKkYQwXvJeHOOOnEoejyX0arqITOBUB1ItYxZJfvYI6KqVPtcNjzXUQJQ3H/fLdHaxDq84LTUYILKFMybmvhs0BR/6UdG1qJCKVkqecZPOi6EyuoDvsZsendbY6qfDtL8orQObYVipMy8h7iaTlAAmUg0A/uWTQ==
    CLOUDFLARE_ACCOUNT_ID: AgCNP2wHcJYQxiHqECNoqdmXyuD/58Xs90RzX1owPX3lPuKsqTBDngrqmGnd1h2wRl2av7+K9MaOi84a0bSsNZN1dXuLc2qRp9NX/fudr06/IE3gNbn7Hi4mtlUW1rfPs9ngBR//XTKdIHf/kE37k8hgHkM3jOS+hATmVTMDP4/OxM2qOaLZnZd0M0+fDzrtEj8fRQ4O1WJw61VO8BiugJ2o0+1KquSdRLeN1SOagI+VQQe852EEo51/zyHsWYbNym25EYS7T01GYfXl8gKx+vZsqKMhqmQBBRneWwzu/y5wQe0I+p2sMwZ7+K8dKSLX0XA4l+GZRKhmJy1635N243iksyVCecEpW5bS4CqnyGjMcZ1QdB2XamF2QOmTBvBzztfEGZnQ4BKoc/SgmoDGCXuFfy617wMU0G3Bha3PRrO1JFkNeu7vKadVqmkq1yfSKYy//m/bDXjg/oWhn6ZVf54C4dC61VGs3iuk44vY7emwjZUMULJRCSeJCru+5oY7EFJz1Qpukr6woELuwdIRjt+PfYOWTZw68U0p6MA6VZvG2wZ176eFe5TzCyYXoEcpHlvGPzp9gNO2dhjtV9eug05GBHhAJ6sAWcXRhRm2DhCG75JsRAVvoE9crsANjOf5eggP7SSTv6j+u5eGxxmgin3pgIarjsjhphNAZ/E+1RfYIoBGX5OO19imdnEkZmOqaOSR+LCf7xcUeg9rzbhgJrIJbUmVUtK9xEIlRrbRT7HQ248NFcHdUErqTRTZBS7hdmUf4tDDvNqsUgCLEMdFnktH
    CLOUDFLARE_STAFF_GROUP_ID: AgAxuY5JdC6ia7/5S+8wxiEZ3hc1BMoTECXVnsfBg2ZeG0l6nbpgXzXZwNstM0pr9RkkasPtKFT0bZ8So5kUkr+vQNntzN1x4oMy8OShY48XFyeFogzVFzR6COGu+Ft/afozNPge38FNxzpmpeqzyjSIAGpOOrMwC/v6C+vm/c6KnaEPT9WXjKeGp8W/hStHCAAjp9Y+JBkix5LlqZdWHyMoF2bqfjNoZRCYqxlLBYjO2hvogBKpHMrCb4JZDX8YEAWYi/CNBt2WJZcGiDI3L7yuctl7FtYCnUnuTSjDsdmQ5/1J72qLr+EOKmU+MgRpvTurv+adh3Jv7PkpCfrPf3RoFuylEbn7ZfHRcSBuTB0c8uL7zmWIvGMsjPpvNJ7rUjLVAyw0cKWQqWzDG3WrLElYOYmjUYM3WpJ7TADO/BLblUTN4ewD18Wh8iZOSyfivem4r1Mx/9nGSbKM9N4Ls4DliORFqG2OpppMjmciBDq+MvSFd+mmhpwEvtDUUexMXG3mlAAG7+Am9AllCksnaY1p+zBrLlaKu0KCsldqflssgBEIuzmf+EQm8nd4GuXj8InWfFCHJ0fsAOuit/ru8FzV8PaBujVchBiux1UnXZYuXB3KQHuRQGR8FUTfZ79rsoM4R7uIeOyYdUFiLADCQzJiRVGiaUbsqe6ZuaGXJjgQBbHsQxsrS9ASzzT45oW3Lpd9VMnOXxXG/GlZNl3cqLcRcswiQA57CqWdBTYdo46cvjYBATp5STqM
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: {{ include "bt-app.backendName" .}}-secret
      labels:
        {{- include "bt-app.backendLabels" . | nindent 8 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "bt-app.backendName" . }}-svc
  labels:
    {{- include "bt-app.backendLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "bt-app.backendLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.backend.port }}
    - name: cache-warming
      protocol: TCP
      port: {{ .Values.backend.cacheWarmingPort }}
      targetPort: {{ .Values.backend.cacheWarmingPort }}
