apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bt-app.backendName" . }}
  labels:
    {{- include "bt-app.backendLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "bt-app.backendLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bt-app.backendLabels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: {{ printf "%s/%s:%s" .Values.backend.image.registry .Values.backend.image.repository ( toString .Values.backend.image.tag ) }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backend.port }}
            - containerPort: {{ .Values.backend.cacheWarmingPort }}
          envFrom:
            - configMapRef:
                name: {{ include "bt-app.backendName" . }}-env
            - secretRef:
                name: {{ include "bt-app.backendName" . }}-secret
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bt-app.backendName" . }}-env
  labels:
    {{- include "bt-app.backendLabels" . | nindent 4 }}
data:
  PORT: {{ .Values.backend.port | quote }}
  CACHE_WARMING_PORT: {{ .Values.backend.cacheWarmingPort | quote }}
  URL: "http://localhost:5001"
  BACKEND_PATH: {{ .Values.backend.path }}
  GRAPHQL_PATH: "/graphql"
  NODE_ENV: {{ .Values.nodeEnv }}
  MONGODB_URI: {{ .Values.mongoUri }}
  REDIS_URI: {{ .Values.redisUri }}
  SEMANTIC_SEARCH_URL: {{ printf "http://%s-svc:%d" (include "bt-app.semanticSearchName" .) (.Values.semanticSearch.port | int) | quote }}
  SIS_CLASS_APP_ID: "_" # TODO: remove from backend
  SIS_CLASS_APP_KEY: "_"
  SIS_COURSE_APP_ID: "_"
  SIS_COURSE_APP_KEY: "_"
  SIS_TERM_APP_ID: "_"
  SIS_TERM_APP_KEY: "_"

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: {{ include "bt-app.backendName" .}}-secret
  labels:
    {{- include "bt-app.backendLabels" . | nindent 4 }}
spec:
  encryptedData:
    CLOUDFLARE_API_TOKEN: AgCQynjMvGbQ8khbzUw3O1/nueLe6vevNLnASMHhi+9clFNn4Wg4Q7sWmNDfBrnnwXlrZlrDFnQLyc8fIjvRWW0fs6/anJ6fJiwnriwjFIhKKzAW/ZEBLFBgoK5j1bEdSpXW6OYZo5zzQg5AvMDfavfPRlqbdqAifyJ64FuafHZjpaTnjtf6P9zEbtj4Rr3oFsb06m6S0JSa8jagpkoc5PVx27+nEtEkoPAJ5DNvCUSvqRcv66FCLVE39sWsjrGFNc+yNXOJNDP886fNqBcbu1dUyT19rK4mu2XZLQ6cgnk4+cyRhUpHuulnQ3M6a3a+2ZFlAxz2RZb8Db80xaE7rj5uidKXAjNHzL2fC3kFcYrbpu+rUcy9TNGy1DQ7SRkB74t/m3NcS+QUnazc2XN5esR/b02hpJg6bFrtcH6ihw/wCIYsOkt6d7Z1K5khpMDxuLKykGc5hcZVXuI8gjKcg2W1d5O8rpI3Lw1Nj3+8W+3GfHiJBcdiLUn/LSZ8KIMzYypFZTyObkxACp0DJgk5pLSu4EGjRyHJ1LjVqw+7uNQgFOjVTc/FBhrnePts9NMEvT0SqbxqlN1dvuPsNgGKqa+3tr1NQCXmDqNZcUNc6yDzAQS6dCKUvyBg8g8v2RWzpYreil15gwl54YVy5PNk8hvPk4giu2HrEDthcH1OkR/7/SIb/coOcG2/e5/6paGSxTfrG5Ej/NMWw0qhNlhyMcJJ63uQW9gXDr286HuTJy6j7JLN8jPXsKWY
    CLOUDFLARE_ZONE_ID: AgBfK8riLwimnS7IeTRGhOg4EtwnEk0xSTrjX22wzSP/bPiufSb5VE04AJgtw/KLQvrH9I8LHXK0wK+WTlgyTl/UIzBdp+9q/l7Cf4/s+P48FmLAd48XV7LsCj/ZOlCMgm84hE1Z/aNf6sgosBJwUC1Nm7c7cZ0Q5GipASVMaVEtBdKVEHEcr/1hj0ME11TRA7iAGfE1s1qXU/MK5h0LfmvubZJkpzZg9Q5Ia921FwxwNmOlxokaNmnzPdfxISc/kv6nZRGBaX3L9DSuMYu8srbZnY8no13KUraGrbGCn5hO1/xpJ5YNjY+mawWSGnkwPDSKNSocb9a2jmwCGeDg/uJAFoe1Za3J3H8wGmu7jVypIhlQ9pAgBcMT3egMfYNngXEmGyfSLKQ2Y51ylb2qICSz7tHIfoVpyUqw8UCx6N3XcZXvc/xKCIQFnvPPlk2VrTJn0LstFd8zIwNOHzbLEEBhBjhoaxCG4PlByOnHD+GI5pTFtWgDrl+xaoTNm7o+opsjTxjwkaQYo1Fc/S/FL+LE75wBv4lydmaV0w+9YHjgUnVgjBRjKMKfsegU+urVKZKtvGo2GZuxkryoOTt3t5LhNZeCUyE8L0bGJdSJ1nOSSauCizwoppRY4FOBFeRIEAYPRNEQ3sUiMHmsj8HMii7MY2npGbEAWo3xPFhFQfNwnSfKTsMbrCgWeVLmD1MKGc2JRR8w+xAlgf2Y3kiwrph+a06qId2qYfUvxYgm8cET2g==
    GOOGLE_CLIENT_ID: AgCIaD5f17vzUH0HcgSot6WQ1a0Am5ls7VuTokbYqAMAe9ogTUq16XFZAO/oOHaKEZGqBG9syWOmPsrOYobMyHr2vXxyC9KuHfi9YfIEjR1kvC32K0hfC2OkLCdOw1wN7G/kICTZVhMJrxivzCjFoZj2hy4V4rc/3ADKVU4DdSULOwet6l6U8sb/FHCb2PRUm+xSkQffcVEWmlYi7pjfo3zc+3NbCNDyOiPAv8Zh//K7EPlEedvP/WFhIrsV6+fudvZlkGrqdXVO7HyHV5JWWAnoyiHGMIbNj1EVsfGuTJFJHRkweIffWrn+3tyaW0h0f6IslXw80XEXaeTgEl27b7Q5OZIILGq+JcM0D+GG5LONyiGXMCG5by4jCjZ4v7U6+rqnXHzipA0Dhsa+a7AS03UmLUjvubmbeQDRd0sFvkx8lkAgEmGeyE0t2DyRHOd+CAsvBmJdc0J9QZ44dfjb8iVZmx0e0U4kCGtJ3lv8anirOwV5y/mgifLSyQ87JiyFxfTIZnLkKRaUpZAM31CBt4sWpdNQXgJALXrJWMOoUEk5MOzfW4mn+HjQrs1EzqW18/Xgyo4LFMu/ZINC//uUBZQsZW4nYz28B+yiWs+MzwT9/JE8ImUlc99RH4rJUJmFMsE/EFf3j+L+qtAOPOkmbQEf8Aqm7hmxWKDR6m5wBga5hWVaagV3Vqr5wjbpwRnIDswJncIHe44HqnZq2lEEeUfHBOENhwmEN3HHbupq/n/RnnmzsvlZW0swkHFKFAFSwMeoFjDKTgWvzEvzK/Api9aFVk/lGxbTtL4=
    GOOGLE_CLIENT_SECRET: AgA61Q+BFWq7xstaVGmMY4B690c5oL5vOnhr8xQyYEgk5gKvk/moT0dz8Wx292ezWKNnR0/yngAMe8rU2WpzcDSOsbU9K4YFbdD6lspzHb4dprVa/hXxF4oVfz52WDHgQTe2eH6AtzPBjn3Is+chGqxSzqP/tg4nqUw38cDOpBDQvLGfseYHRYZ2hqkaKO7Y/4LmBiGWMGTkUhzBCcpBORV16NY0cL5lj+7WDnsc23jBkBQfI+rmSnqTnUy0QbobT2ovg5C9wUCxBmhYzCeRoDxhL1BsKtn2A1M7KablbyodYxnDOlBQW3Z1Jc5vvtEWleef5HX1d/WLNqMxmqPLVBveOoc9TqwUbTKOfCbXWw+4Mvatjw3WFCOmsF0nnP3D95tgJm/63/grbGnZSQCSs7oodYs5XbqrECKEg8y2C09h3xpW3GlUJ/TPWsQ2t9hhWPow5iACh9u/sr95g0Xda6rWbmWpEbf1ozfp2XMdeL/44MetcR8FmQhaZljL+OSbv9Kie0gjt3uGS5gm+m8c02SKIFNEdobx+7Q6dsukV2zq9pQtOSHrEgG/bhWtpi6eZ3aBxN+JavSDHdWM/LZZ/8A7CjzBKsWi4PsBjgdFD4HBkdPiZsXVhGkCbHyn7dCTTTJHt/xfhbYvKcdTCUAn3LR+0VxgtKV1l5mGL7q7A2VPDMx0b4djaW46i9PX5014/KOvHmlQhaK6XZJXYdrS4KotfPsHIrVuitI=
    S3_ACCESS_KEY_ID: AgB+PwAvcbk1/4rFIoQDuujbH+96/pxYfYhAJ/LX/S6HRdw/no7T90txlXvJGRBiUddJM7PzPTIQ4PjD9O1R6rPd60wZWC3nwFknyWhKo4hp+FOWz4CDygJrmL9318TIQMsnmE8o12aXXi94De9399lltTCddGagRUllH7PM9lrd1BD1qYgwlQhWGLdlYDU70BuElEzlfq91OH3LbjT4XEjXeC3J5HZOvxwuLvhb7Wy7S+TcsELj7suMlLHql3um2m8AFptgNzAKjZ6g0cUejo+Pk7E7EfUW/BZnFKccnutkKIX/u5ym8afpKdNUeV3lOK3uxaOBi9V3v8GMlcYhgt2gdh/+oz9RbJyTx1VNeuwR77DX/QidYyB5XoXN+8+8lxm3vszHRm3Esv9KBPIg6HhMk+q6z9Ig3kqHrvK9anuhV6uaoT3IJIBnunrCuAHiD2PnBcpaHnwt1DJCdw5C6cdOD8F9xUrva88Cja74C5kUqblKHGl34E897exw8yBk4s+PIORTEatX0gkSg/jPaF7QIr5eatl6/0I/GQ0W1Mly5DeIU7fz731pqYIwCNSha7yVCyf4X+FuCU33jG3OVW6K9YUuNNTE6wtJJdp1cpJUDf5cyVIgAOKk3Tdz2J/XSzyG9vtQmoaMWZAUequYdIiwDiIR323Xl2wIyGj4YXWrqMO+hJ6iNx1mKzoqbulP3YGyG4LbPQ3vzVWdVcYCTMsQZPEDWkKAZjQt1LHheOPeNw==
    S3_ENDPOINT: AgBUWll4MNC5Ga37/gJlrSPst+iD/0SBHNherR7ky3sNQHm/LWVNFS0rLEkP8XZHxTKkQKyqGmje17W7xj25Ysd2Ve0e2XGwBqzNpT+C1dwJTl39aLxSFXmXGyvyTD5C8qggqJ0hO3mNv2J3rPKeFmF5GJqM5HC51O1maYQEU4UMsxno94QTCso4Ei41SKyDJhYUP25hfysSNvxAg4nsYDWKTmx5ncOHZn0gxFhcEYYVuyrlR/lpJyUDSJLXGVTfX7niLAZX9UQD9FAOEMdrwG9w9kPenWvyIUzYtJP/2V6NH8V13WZXOs9XpCqJ0W7GVx3eLVs+8HpatDxUbTrczJ0GJkudf0X1V9nFoMX7INU2jCobRSxHjqsxXee8QvX+Edxy7g3iAhK01atBydgQUUwjJgy3Vhn9S+kKQmss62jXjBDh0saypqyX2tWU9J99l53WETZfLJ/uOaXH37ZRG2HH7dHuaF+yU9UbayaKKPWoi0dQncN5kGwU6L+ebazZorfRsnnfH71wh/NMFt+JWeChu/EqyQLkGcjikD9g13u/bSNpoE4wTpVb+cRXp9ZsmewQ8ujbVdzNtjTlnL9+LTRpqTgDQ55efjVvxXsToGAYa96WP/Qfu9K0ucWG8n2rqlZVwvBlHxTsrVxo0NYBjq78E5bwmWBuAns9SbRM6pW2wshMO8CAcrBLKts6qQ9Av67YBG7jKY6GVRYBezjnFKb893r8kVTZddDUXfO/voAIt3TK2iifrTu/CQOnGoBzge8B4UsjUisZeLdGoFRDAMzHfA==
    S3_IMAGES_ACCESS_URL: AgB7fV5gjUtqhoiyLYAWSX5Xy4HTiCHIJAHy4o8owEFktDOf7/VCNMbIs6jdKSzHW0ak3TC7lFtEAxbErNeC77dZ5wmuU7XJ56sXoOE705R6u82iWp6JF2Wz/HImz742QYbbeUsm8rVe6U7cOki+XoVHQuMOWFlyD+sdDcuCbiVYzU0+vXilvpp2zE8XvmiccNtDFI0Ax9b2cPxBWxUBqu9o7VeRkK3JaKM0n2iaFz5KZaLsc5+Wf0gSqRchkUSVtQy+qrqQxzFlzIcAMSy6EsXv9fFRpj+F54j8n9dz0453hj6ReyDgif08WOYP++Tm8yfDDKJv1sFxHulVo4mK5b4E0EtDMsEPMsI0S9jRexqD4ktZLj2Cgnt4TKqjG/fZCJYSleJrlyqELP1AW6X1vnZX1wc89pQdUgd72QnQE9k0LzanAOIPoWH6UngIsuXuprUl2nt0vTN+p+BXxp4CGh1etgxvGUXu0MNbGrOKf4bdklPYp84y+ksSHlssuHG/2MkpH8LKiuB/Vqncw1oM1NrIyh7258+xeZOhpYIhnkNrOC1RsWbSilXfstk0dADcsvafEnxv4UmvcF/M0cWNYZAlpEvQGIrCE6s2c1d756RSGUosLvqzFZyl0oQU+UPaTPitav2OH8HehpyK+wwJDvAlTQIsI4P3ruLVk+Apbp0ai+qUgj8e193PbkzjhZf+XFg2b7MJIQ7XgpTro0neUEaJdcHqysSqSZ5Va/04n3Br
    S3_SECRET_ACCESS_KEY: AgAfwTOHE1G3YgJoduH5qHhgT6qocn7drfcRNJmSb1L2tGvp/g5ka/O6AdjRpBvhNZdqhMNKPwdRUBj7msj1tZzNlH5xNVBigpUcRZfmGXwkjuoRsUFgDAC3xptzBgqAT7L32AUOGLgBmrH02aFRbP2Md9a63go3r6nJgn9Ks4qvCCZM4Wb6fEgcD9W8hpse2FKDo9T3x+fF8we9wEXB/9DGdS9TRlIjeDgWmUzh8xpRz0Ey6Gcg4U5xrnY2WW71uLcfi+gVvqira6bI6iRrPTWC5gdjsIve1pqFAp/zk91qKCvKrfdHsZlZeF6dVqjez31qsAWRJ6qRSM6I+m2AuzH+GK4St0q1aceW0ChuzMuetCA4wc+xtqLjE8q5WrYMLndvlcvSNRtU/m/s4tEFMqEJpSTkY+w9YTxfYXxypNSglr6ZZLpgvNoZAS9bKxwJX2Wegtewkleru1JRrZZDDgUYbelMX6dbzHpxUuOtpIvzxX1yhiRXUEXaFbUdWjIfNDiY9d7nu2W4bIprmEGNYRuCrG3shJCROVg6pRYei9mVdWxl646ii3WvOiESZgneTYYEi8lrOmAc9zv8HvXvaKJWNmVdYKDauZTX0kFkqPAHJ7KvczGVlAKh6EkFNrkfaIiR68CM17GTLe+nSRafp+caGjJGdufpEW7/2aZDQc1LVNV4yrSHdInDQwBimj5Oo5p2XrR5rI6+nugFHHRzo3AtHH/RSQMrHbVZT33xz7ZfXnJeyxpPDkN7igDnh8ktBSP0mdEDwyioXG7KLANcUkRa
    SESSION_SECRET: AgCIHYB4oRaV+c4lXUHx2RIaCOFrexg33Ss1oGqzf6LquaRveMFzXLB16Vc0zxnHmCEND+yUEkdDEzOHvc86tK1d2Oom3r2JFu8abpMzIYxCls117jN2BOGycrREAfqTROSPr5SMJpx44Q30y4P5E+FjD1BtyhF530gcMKgr19OjL1rDfkl2sGrWSkcUHNMEXKTFhFNAoSakmZWS8IbLLNWM31kxUgt8cRSEvFFeIxpAEVPer79wUxrIAVkHE8igY42Iab1uSBmbYSoyREfUlNICm/7flBkDx89ADwOWZoU/IV3ewViiE6HysjXhEPY5qFCKh7SBsNEgZzMAoQRpkX+gFPSvgJt/HWgoTuFuKFODa1aYqtpjRC7Rg8iIJyzxBTBBk+EPE20DPEGllCCvAQuUPGmKFQ86unlaUznWQbyXaqWadFG0l45gePlmjDshVd3VXeqcBF6/rPlN/lUlAg0OJgo4H7oGQ0bOR56f/1ms4nCwQNwvYP3h64BSGi+dFJiEJ8bnTeAGr2loR7v7WmtHQdX7iAdzN0iN8OJAGuP9wOwl1kFUFshJAjbnCS1iKumrhRvxVsP6okSB2KPs08IK5eRbHjaUg8TqMQrqKQEFCU+wHq11EfZPwd0k3ZLUyZRTCEQUgDqLOwrMjvmHpNnHctkJn3XD+sLODmXVsL/3TBEkdHjB6oN26LcZZR+m+Ar+b1rIevF7PDVe
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: {{ include "bt-app.backendName" .}}-secret
      labels:
        {{- include "bt-app.backendLabels" . | nindent 8 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "bt-app.backendName" . }}-svc
  labels:
    {{- include "bt-app.backendLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "bt-app.backendLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.backend.port }}
    - name: cache-warming
      protocol: TCP
      port: {{ .Values.backend.cacheWarmingPort }}
      targetPort: {{ .Values.backend.cacheWarmingPort }}
