apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bt-app.backendName" . }}
  labels:
    {{- include "bt-app.backendLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "bt-app.backendLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bt-app.backendLabels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: {{ printf "%s/%s:%s" .Values.backend.image.registry .Values.backend.image.repository .Values.backend.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: {{ include "bt-app.backendName" . }}-env
            - secretRef:
                name: {{ include "bt-app.backendName" . }}-secret
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 5
            periodSeconds: 3

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bt-app.backendName" . }}-env
  labels:
    {{- include "bt-app.backendLabels" . | nindent 4 }}
data:
  PORT: {{ .Values.backend.port | quote }}
  URL: "http://localhost:5001"
  BACKEND_PATH: {{ .Values.backend.path }}
  GRAPHQL_PATH: "/graphql"
  NODE_ENV: {{ .Values.nodeEnv }}
  MONGODB_URI: {{ .Values.mongoUri }}
  REDIS_URI: {{ .Values.redisUri }}
  SIS_CLASS_APP_ID: "_" # TODO: remove from backend
  SIS_CLASS_APP_KEY: "_"
  SIS_COURSE_APP_ID: "_"
  SIS_COURSE_APP_KEY: "_"
  SIS_TERM_APP_ID: "_"
  SIS_TERM_APP_KEY: "_"

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: {{ include "bt-app.backendName" .}}-secret
  labels:
    {{- include "bt-app.backendLabels" . | nindent 4 }}
spec:
  encryptedData:
    GOOGLE_CLIENT_ID: AgB3hUixkfGaiuSE0rwwFN2TTAj/GI8cZpT5lTBofHfJcqtX1z9XnW8zDE1prfKKv0wYr7TeyXC3qe4UuYyOjZfdpSnNjjkJ0GW+LFSO72jmsQM4PP45bv7wtrTMARg7vHqMjIfvu+aJ/LvZ+vD0X3J7eQ9T1cniVS9Wo9rafGDWVFCg9cp/NyhQLTjPCHrNj+hw9GWj9uo71tHKs+nNywsUyyKTWSya5wIAqiXSREj3qjOGKXVJH3tjid0KpDrPnL4YZb6L9bc1GSFoZixAJMZfXi7kYRhonmcAQtnKzWyxvTDINXZ9epktYJKgfBH9ogkcEBv2mLznbyWJDFxQ4niCn3G/2l8XzPaf4TuHKDywDI1VLPovSLplIYR69YnwKJGNpZovdei44HMjZWtDY5GB235vzfCSQq3RyjXPG4bFF1dA7oKmuHX1Nfnw9Ezx9+xNtXRDwhqaaikqgvboFfDPl6+5MUYqTg2GlWZ5B0BncjhNofwJsyEl3B2VL/04gjm8YvYZqHDyeuGZh9CwDdixhNFYuN5ZqYDmCuVGA3vJrkEwT9XVfZ7+g0v/gQWYghOPtepiosfETH9z3K2xOI8mQw2h1yAZktRbMNJoryrcwLnX5PZ5zPVn/EVHcnm1BTQhR1NXts9fgwCskT4XUg6JjgwuhigLi3fhJmyLlx3d+SBiyOhD/a9yKMwTslHsU+ui7RbBgqC0FvFDF4cHpTtALZaxqG3lBcYuZdNY/PUxWQe+T1fYnLRmx5c4KrfU40pb61t/VRQ8Tcx2Vl/+4wozaBMqEFd+uU8=
    GOOGLE_CLIENT_SECRET: AgAIVj8nrm9khe6045NX8wLNIXZcWKPViouEEAvaHYUsulEyX738L+6nitd/YG99U9pRCAdErTRCNG9gEo4/2nLyOaWRW0jJu4bfRc+gUCYOOU0Y0znYqGmlGdFpxjdNT3eFkxkkLDI4T6f+FmLBoTRHb2bIFv9m8263ESuVvMfqfeDJWOgo+5LULNBLHWUABFE9KinozrS7MtmVm+GP6QioCG+2PsOsykRwyLj+NZqhwiYcRKNtwEOV4t21mFeWORxAxSAjFxALjklxeCyDp+XvkSglbT8G70DQsqtMu6xeFjf9ID8GS0zpVf9vjXv8Up840BgM3cHNlTgETLDhQdXzGfo/Rqj1CpekgGLRQOElkYACmzAOyLfg1ws4JiHGaQhlFlnEd+5B8RqIFVy/wgYxK4mY6XUGPktUzW5+SiVCL8Z9rjfYWg1dMgFrY9z2t3rj7EUvGhuQGc/GPSbytbN6p0LfuJmNPOmt8EC1cf/7+5Cof4XuR2zC+9JFYiBiBupmbyrS4win96DDWrRQROVSELb/LTvRiTYwBAeHpPZgkxexc9jEZS+iCC1PlRP3+vuGKAdv7wMpN/kjAe+vJxo0QSVudP1/QJZP6ynGGED3Y1Chqe3KsEeI85q0nUkth29bke+Z6kEHJHSGIMatDx1rET1UsxgWrvtrE2e8j7MYs3RGHyygz54/yFFONbxuszbs3Zs44xOm6lXOZ0IsFfvpPph7X97MfaM=
    SESSION_SECRET: AgCDXmthhXWEjKsbJ/LzWtONKeqPciM30Hih2NXY3hJPHQRyKkOBQP2JXfYkLqtFhLjQB7PgYBj/UfNsAMAapii+ETipPZatBVd4GVFd9/3JseFwqzUTFI7z3LlFxDYqatArkMxksuccH0j0Uuo4wOIAJD9rhYI06001GBOqUIC4aS/oICp0IGBXedEqQmpik10QIR6CiJ26HvkCi2KPp3mvrgUrS9bP7Mw11xMfH4+dN/I2FOFtRVyX9T2eUbVT8JliAepJFFexoudFY5EUdDJ1Vtos1Beb5IwFWnRnrcoYkCSPuIwjkWE2kxPO9X87PwupjzP3UjEGJUFzFzxUqEVNNpFxZsMPVxeYnrNw09oZpIiTxcxrWQAKPh3QNDdQ2cuSMwZEX8NSN1Q0b8Je2l21oKgeMwR4sX4oR+45ucW3h9tcVz7s1BwSmBxwwR2goyiTzFoTMQ6d6lH9d16N/ZTcrjlj1mRlQLuZGz5gQLRY37p7OE7XvIHVvU3+r4fDVhdii3YHak4qMF+mEYuBRl1DyJzj6810i36NzQ44EwWuKs3VOfmnIa5Ov2dC1kSrwV6R/6h84KpfmH/Rtl2WXoFmDq0g1N94i80UxmbrCe/82j+oShZBEpPaf4SMGx/vhqE5cFUyEOAKClPbIwDfJCk7d8H5OAlQwztc1LnRt9iZa5vlnipYQ+33LlCecLE7Rfijdxe9d+1dvk1i
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: {{ include "bt-app.backendName" .}}-secret
      labels:
        {{- include "bt-app.backendLabels" . | nindent 8 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "bt-app.backendName" . }}-svc
  labels:
    {{- include "bt-app.backendLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "bt-app.backendLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.backend.port }}
