apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bt-app.backendName" . }}
  labels:
    {{- include "bt-app.backendLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "bt-app.backendLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bt-app.backendLabels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: {{ printf "%s/%s:%s" .Values.backend.image.registry .Values.backend.image.repository ( toString .Values.backend.image.tag ) }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backend.port }}
            - containerPort: {{ .Values.backend.cacheWarmingPort }}
          envFrom:
            - configMapRef:
                name: {{ include "bt-app.backendName" . }}-env
            - secretRef:
                name: {{ include "bt-app.backendName" . }}-secret
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 5
            periodSeconds: 3

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bt-app.backendName" . }}-env
  labels:
    {{- include "bt-app.backendLabels" . | nindent 4 }}
data:
  PORT: {{ .Values.backend.port | quote }}
  CACHE_WARMING_PORT: {{ .Values.backend.cacheWarmingPort | quote }}
  URL: "http://localhost:5001"
  BACKEND_PATH: {{ .Values.backend.path }}
  GRAPHQL_PATH: "/graphql"
  NODE_ENV: {{ .Values.nodeEnv }}
  MONGODB_URI: {{ .Values.mongoUri }}
  REDIS_URI: {{ .Values.redisUri }}
  SIS_CLASS_APP_ID: "_" # TODO: remove from backend
  SIS_CLASS_APP_KEY: "_"
  SIS_COURSE_APP_ID: "_"
  SIS_COURSE_APP_KEY: "_"
  SIS_TERM_APP_ID: "_"
  SIS_TERM_APP_KEY: "_"

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: {{ include "bt-app.backendName" .}}-secret
  labels:
    {{- include "bt-app.backendLabels" . | nindent 4 }}
spec:
  encryptedData:
    CLOUDFLARE_API_TOKEN: AgBDg6unya+081d8BdCZMas9BgtzXuOdUbkC2bnLV5v0hw6PaBHYb1pmANcM1Lm3VtueDdGfNV5Pb5n6wVbNUQMt4jyLl35NNmJ4F/buRkREldSfCvOlgslSMARjIPQprPL5yD8UCVTilOHaRRA+joYGc/pANy/vSeC/UJOiWP3nmzUrPjDU3rUtmWYjP59t5FFxK55mr2n2wCiur9OyFdrB34KNIox78n7TaHTMI5QBD84yoZqVY8k54UmRnWrIN6v4SwGvzez1DAx9kpS2SVO/2u6HXiu1cPldNTKK7X9X2qQD/nqHEwRcLcOxbFtfocjVSpFV5HJw0IpvzoojGLSJlvZc0tCF0JXIjdgIlpoC+yDBpa1NYtwSPxVZsyzFiXradxjmwBQu8Yb3h2QV2G4/kTC+6BPqrOHxBo7fjAi2nCLl7+n49QEvsj4FPZZXB5mssb8BJ4rtjNn1rwfDAR9wUKU+K1OcByAguVKTzYRGIZ59FcYWhdb3z5ktWOQwhzcr9UOE+XMNiF2Rq+QmTvXUaguC3dsELb62VoHcflNCzUJvy/YjJsZd74VEMw6T2kX6kHjzQynd3cA7yZjABiumBL1wHZVkicwR07fcol0rISVxYVixrQPWOajNl2caZYOE6Di1UC2jMEf9bqU35nhqEZWzpo85OLYBhPz8O9b+Du+dVzBAyCClZcEq1RYEU7ySujEfNnEcLQlI1J8G7SwNsA+GXDD2n3kufTVI15/EXQkCvsyhERqP
    CLOUDFLARE_ZONE_ID: AgAcpOgJnJP9Nqb1gXZOhAlmNEjUPx9/QRbcMuaZ60eb2IolwlA59oel9ELXgc9cyL9Qx88bL1ueRxvZzG4d+749Vu9tPkUIt5Yboj46RTrrO2m733hVZ9HTI5W9ExK5hPyhd6IXGY/5apt+NBWUssWdHW6xbawTnucBpSk0In72Zax03TLwuJmZMLrofTUSB5JtgVxTa3ywfRoCue/fYMNN3PTm+gFLK9mk0o1Ex0EaAqgbuEh1n3EpMHS7NJd+4PvliREoeR4AgK3QirRcJwtO9sM/9Es2dlDqoiGVsWUG+/WFVqwwaP5fQKUOKXLP1pEQzIHj720Wm//zcfNA+LysUfQe7MZ97ApOu6Ee50q25lecq+QnVXZcQ3eNjLYLOA585IotmnD/E3BVgrwsPilhVqLJFjczXqkINJQCqKsvRdJeGobuCSLxIaSkULN3OChPxxFINjaAsuboW3zmwyVdnws0I5u3KfZH6j3E5tviemnfEaVqPt5aHZEJcB7cKWJvG9shXUovoatC7nEHjVT3sn6pqzPCmSb+SV/PnzQt0fIYuYGaRhIIOASfNN1rLdXS9lqqrbWsvpm8k9uGqjYpV0NzkaacZ3scHdhXHvjaHTGYVlyTF4oxQu2Qj+O/rbm9kbOLYM/97IcUhJ5oiQW64pcGqTu58vd8EAc4iEFW+JMU7I+ZzFcGOCs1i+ipyZUUaayHGZvJFC/13sEHFi2Yhxezon+GJT8lfA1qqg5hIQ==
    GOOGLE_CLIENT_ID: AgBuwYKjtIFIZUHKWQXYae9/iN/KGNSw80bUKicWFv3jz2jnSK9YHu/2cpt9dlOK4bTfrAVibCbmj8maDMsj8S3oHO1iX2TYVMwVDnzty59XQ5IPtStZNUUY7A8e/VT4zSu7P1h3jVUEMom0YoW7nhNKe1kC2u4bxR7KTZH6yoSGwWm3pUNgUuAUuFgEV/EZ+k8GLcaNUDnSnVGyQf0Nu4CwzKYdM0+ugDDl6gE1NgwA8iw3YUf9R2ZWDdIscDtpG28rDX9YspktreFABkUGbO0asMxA56SA1DyURQjzPK2yuB+rcqb2wLy1v8LG2Xnoyky8eJIY6FsKdhr1vnqp3B0mPYHx2DvG3qPutBiaJ/2vOcXJIenStG/FWTdln9UGzLrhzUbk1+klxTRwX7OutlOvA+0pAKp9AYtn2f1sNfgVud6FRpWMlX/pQtSArT32LrdfqpPhdGjWGW+UpREKaI1PfxEd/LxQGcuU77l5EEWCLWdjWVlS6mDb8A5W2py24iH/Q/96DLr/GKhJjsIIuyteaR0xtOxhY6liF/pyN+EEjvNkDtNQ4/hyGXo/565+CzVlX48Mrgz4l045zQUSeNdm7llAC6zZiIXvbENMsnAt7bDzcWiPczPFy3Mw6R/UOxLqPOHFeRqiJR0z6JYK8DIdUZ2vtpCB154xXW6SdwvVw7GyxwQIvind8LwkDgc9KST7VsiQ+mdiyfD44kPJu81XiBk+Ruhtgf4ZkFex/IMSwk89qAO4maykH2/m06EAVO7hOg9nwB5kCY8YpnvXXWIthB4WLPxbBm0=
    GOOGLE_CLIENT_SECRET: AgB1/low7u1fXxyKR6kdVWkouEkfM8OZnQpIqx99zeyEp8Vhb+V7FekFceAakj1JluaknmP4K0HMize2LZJvvG+Her9NKlbKio7I8tkWVHw+AgnWHczRztcFmK4OP2gWDIZFTfBAD/jGtnQEanB30Mff1gLYP/sUOK2QvoHZxZB1V0zK65n8RHYSPUmgSAYiLIWrJUH4e6o1bZF6z91EbMVunWiwoKZDZWw9WKWsLtbKn0SlhBmFzVTMaBPj3/cmkKhj6wgdHGx1xHQ/WjAXsifd0EAJMzKLJGXMsjAxpdxORqOlsoBXDauf8UXGGrr/X2QTBJmsIw/lSaHIoIf6XBRjuRZhqkUY8zqSV8NIBri9DhMmb/ac6qN/hd4wVegH3y82xDpoeRJxpcvZqGWSD594kRPCSnMdnUxbFC6fOfHixmXujRComtjfVfaAufGKIjsmR6iv3fyzhOpCz+H5E8gCZRd0m+Rv81nIeuRu6Ca9xAMr6LRO3vwH6ZRfsB3RlEqs7UMxDLQtRFfXethg7RRmmX4C1e+d6dEAI+yUnhl/Jys8GuqBnOMglKF9qUxCcTkPkSNbQQqezvAKP7tHx/gRwc+qlk3KFU+sExUBp5Q9hMDwqVdyzfjrcvXCVAKqfTBPactafRWBziRqG7Hd6jD/WALv1nYpXFkTSkoiR78EKOMOEAr7aiexDPhY+yBbxdmUzo/GrbBbgERz3be0lFnfpdLxx/3Zst8=
    S3_ACCESS_KEY_ID: AgAZhYyVWl9ttRKq6N0DHVLkq201P0AhNoL8C/MNjy7VqoCByc3D9LRc3vOsZcxPxNn5NVk7wkKKgKYPODRZoNCVDbTMGyon4sMmQB9+ERIACCcYuRpJmoj4Qrw9Q8t2EzAqF1PDFH8ZcfzVlSi9RHvK4tMnQTVC3PuuilzO2XQgyu/PnWWS3hnHf32S2kREaNxswcsf2N0uDd+/EiFJYpPX7trQUdjYTG+S3IIRyMvTWYkipg6eqxKsWvY1QBflyb78T0rJNA49CHKIP3BQfP9Rbdk/DEGxPsNCxXrFelwOwjd//lOAY4UQvVRa4o0C4RAkxlzfUUsQ5/4qk97y/TLVoIPh9CMNqwNZzd9mdnqkiccOKYW2lth5y2HEtktgWvgavEPIWxkLNNB1b5qxWwV+cWIZ0tCiZ0FNTOckugyLs2BnkYzky6df1AyNhzNU6F/BtnDxh1ut4MKSyBOc5bqRnvKoWXrblOjYMUPGe3oHMJN0190HuBwQuFr5aNllq1c2vubw+eZa7ch38SjYLoALrQwTrpu0iWGcU4spE86w798euKJ6WhqoImCPyaUEU2d3ziWDLvKFC7MUVtsJ9M3+toWL20EFFPI2nhJAn4Daz9ZcO0kEOya7yu8IxSZMEVUOE0O2tZ3DHmhRiHtG73InEeGKvtfq90kitr/IZUnr0YynFguqrvu7FTH3U9X+bAfxXQuW
    S3_ENDPOINT: AgCMXbdYb3fZOKUb112uml7hx2eUkkdT12NKlWctwAKyAb90aLzciLWQ2z4B4cp5/JhvqtcWDD0KzgZs4UIzfOvfMNIPBdxEq30A5per4LTmcABN9v+m/NndNM3NxO7QrddpmItits3LGQic3D9Ab/Rkj8wSdJQze8oELrbe/DnITMztaqd8WDJmudt5msb/elPc0wTa1OWXoehNdUaLK0wIWNlr99p5oojWDHWrhkV2teBVF6subRr0DekEc2TJODA7aozm7F0KLeKxlDB/drc+r8IrKQ/i1J3jaHm2ex4I8q8Cr+gLRD1/wu4EBvDiWZt55K6v4fIiQx02PgbRmmwRcuFunXBiaxvK7Jzvbs34YbXe5YdoenwLAzjaXr4WvJftcN0bMlynxZUpRhLExv0aEkQJgO5omNs2SVNleTMa7T9t24ij50UM/7xC+9+Rm8FqQ8Vc0scl9H3ZZ/VO6bn7JuR0UX2pne0/8IUwKc/UYL+GwqkT93pAKo9bvOl3Ve5QsD0r4dr/FIbedlEAWLhN4GXbiTinSLnVGZSVff8e6E9BsUK1u6xOrpUn3FeEJfg7L7kze2/gbXOWt/hGwEZeW2K00p0lU5bFAfNIULydoFgwGgjRkVqHijTKXdeqYmN2woEs3wYFnQQ6v6/5jo91nvaTqu5PIwd0gVq+qOIxlHPrL7jUNw2qSS1Gby4MTKsJySbqmaI4+STXdph8OX0dew==
    S3_SECRET_ACCESS_KEY: AgCQRm9znuD2W6h9HCljNAxYK6XFVrnztUkMypqiV5wbTlpeLFcXtnQAx9n87nNkZapD9aiTNfxA4IpTcPFmnSBbKgIIB0Otkg37y2uMxY3fAxksVUCrzDrUsL5C5ictjpNVsuLdfKIQVUQ8yehgltmZ77n9mpOErAr8BwB1YPmjrMDAr6uO5+oi20QuzVZ9U512rfNSznpZVIRn5CpraGgW065ks9sYMqIMtHVm1InoV1ndOeuWUvpVQFrsAphii7GyDm2+HuYW+LEar6RFcmljjlMB2Wl2QFogSF3NG3SZQUIQYk7urnggeMGyNIKJqtVmkkXmlfCnvDlLSfb9U2NfPBTcBf/Okpn/epmVRkq6Zk7CuXiUKr4+vnuMkG71Mn+SVwrSaOQRUKQU0xTYcSmI/8AhchktepJT9m5qVDIYCG0yq9VvYk1jbnJWG+Modpw1XgsriI0mWI8ORN+eLM7TW/FALwfdF6h3gEgYCeOqq+CDnyNiwiTFoGRKF2b3//HMqJkxSqzyKFyrPvaYXtrT0xcwkUXk1GcUjjfPtHcrOO6csloQjl+JxldD00N+c0O/HHe8EPLBJCOQn0ks4SK6VGuEO0t4UxP+L0YG7y18Zj7GNdRwuPqVCdSYfIQS/Nepn/T6uNJAuL//2y0/9+4bw4dX3YYhpO0u4XJ2ps6siFuGNM4xnui+rfL3v7JEnapxS7NTa7/wpg==
    S3_STAFF_PHOTOS_ACCESS_URL: AgANUx6ZM4LJCfkDmO6BtAc5sqxTEsCIHg7fpBRnFbQfEOJo21K70W6DFm1HVUd+QVP5itnGXVS7davcuPesrhwbNYfVnakxAyG1FRdGC2+v8Nz2OMknjpEX0VINBwJURR44eL1hvLwdeF/or12hzUfHRimBgr10U127mKuAfRcheXK6kwT/LMjUM8J2OR17qVQ80ISWMQBbwMNM/8HmE6CKthe4RdNyxz0o8kHyJgJleL6NbWDFqY9a3u6e/s97JF3k3HRwjDS458Sl6dBVnNd/FfDohERRcpKGtnskudXDVOayXWpVoSRpbZzFcIIDm1iA900OpGuP8KNBJ8tweSJAfFoEC9XuclPpOsJ9tFrTle+fiWPxGh5nS33pefY5pGj1LIZ4fZ9jYawnsRsPEisVq1Jw6fEXb3bJmsiRk/IsU4/6cIXwqVsuzWSdpflgX3k8NJDeSYAH4MshS+e/dKSub6N3L0r4PvhHFwftwGSczMtGjhvm5EGPQFxhFJdIhCgDl8SPfGOlb4fN/AHAm+0hJXO+MmIx/Ce7cbdt7REcRDgz4vXAs67guNHGazffhQ9LrTwhfw8kxTFhtdqgurA3H439j+MOz5fbq5uSYhItpqGKId9RdcadSsSdVa/jggaXxfkRjpV/aotg6r/peMccOLuOgrhWfrr3s8klJ87+BhkNEKrCZ610qrDx/+x3JfKlR2eu078vV6WwdgwPtr1VKAsUWwT/BnGN7J3U6Zv5ajpU
    S3_STAFF_PHOTOS_BUCKET: AgChrgZLZ+kmSLCyel7V6sGsyegLFzG4OTX1tlIkT5TpYw++JyaHXdFbfmCebdqC3PKqgtMcpAp1o67D94LK2lioNqfJHqcTuOQLWhn3dmiXTxKW4Sx4cg/Y+TZI9wnjBa/Zg+cI0or12qP+86Vgdh1YqvMZNTk2qC7DAKikW+naaFUBiv56ZWMPfV0bezvYIeAetd1nABHHN8YUXW2xSyQIums2NFKYeKkuNgUvYNe6bNjown0Nv8CyiU2bYdFXGpckZdWK2x/p41DrqwekPx9UlXEN3a+sLRFMKbc9QIFkGmALGMsAs5f3a43YSuR6crZrmPK+uUTucrrH7i+gzOUOue7nRJY8sdhVat+b0lqVkBRbK83aEeh31kwPL322ArqJsyNX+i9sGZSTH0gkiCV1kyNGzY0Dzt06uuJevV/ugSzILEvtBbaOj1eCsfTpDQNGaqNgN479zyG93VYmCQtfsRK8qkxZJShzzPdW5+axuUVNnh5F9t1m4dIM8JL0bvIz73BlWukF4lcelviaE9eOrgqmzOwMLVqvCf8p+GH9JCRA1as0KCNg2jgkevSg6HieiQx5D+onyWNc3NkbXbT6xSD8+BPDyVuRocFVkXSOEx8tJLjkD6Q5JG/G9Lqy6V+YqdX349vlz17XoC9VKBHrKOR2ZGDMxYsa3VteWPycx/qphyEhKKTSpfKqOS/iIcDvSkCdnl0GXhBxgLg=
    SESSION_SECRET: AgAkh9bU7Em54fNeqg8MOevYrtZVV3Rrm/2yQhh4h/6ixGlanmRTouqoSdVhCf+XMh/r495quIA/ZJjEgTjYLl7MLkzbe4jp6WRmNWD/XZFWvYunBxR0+yOkZb9plaztIzqdRDgcINFHTIzlMQVYz050tWpoT2Dg6WOx/L5o33fCqLNmnxfiGUq2TgxJlXUmOuRF7uwlXv/W/tt5Wzbx4EMYXx2FEFAOi12ufVb8xcyZ63a0A7FMFIS5HXhJWpibQ9RW60ow+x8u3ib/XPnCgdHV7iD25tZcs5AWWU+YNbtkKHJaiaJQrwftJh5rUgG6gwXCCbOVCHyMFRWQg/FTIXLpiVrXfFpU2s9BK+OC9S2uoYSAfutNTWtUdTVY+cgb6XbPgmO393YXiOoLS2hErNdanX04YiMHH4n20NMhtQ8HS1fBtT9tZ/J9Lag4hwe/tbSmSFVwvID08FzSM7uMxj+F7KnaW32mIPMCP/U/EpfaZma4CNe2YI3R9wMGkdGMQp5QWq+DMWjK2Gx0AGAaS7DL3rfWYIHK7H9xH4T6L1vNnUeZx1kqXePfdS8xyLOqQNXKNViQKrgthF91rn1c2eLzuP2wV9YNJJGyuk0bv9Fw3t7bk/FRJVzMtV07gxHBAuCdjiaGSGS4uowpOFVkQV3MrK9WmdE9gyJP+pefg48aHmSkMXk/R9OFzrW/ULpBi0gWbu5JcHhyZWtl
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: {{ include "bt-app.backendName" .}}-secret
      labels:
        {{- include "bt-app.backendLabels" . | nindent 8 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "bt-app.backendName" . }}-svc
  labels:
    {{- include "bt-app.backendLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "bt-app.backendLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.backend.port }}
    - name: cache-warming
      protocol: TCP
      port: {{ .Values.backend.cacheWarmingPort }}
      targetPort: {{ .Values.backend.cacheWarmingPort }}
