{{ define "bt-app.datapuller" }}
{{- $root := index . 0 -}}
{{- $jobName := index . 1 -}}
{{- $jobConfig := index . 2 -}}
# Do not run CronJob in dev environment
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "bt-app.datapullerName" $root }}-{{ $jobName }}
  labels:
    {{- include "bt-app.datapullerLabels" $root | nindent 4 }}
spec:
  schedule: "{{ $jobConfig.schedule }}"
  timeZone: America/Los_Angeles
  suspend: {{ $jobConfig.suspend }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: datapuller-{{ $jobName }}
              image: {{ printf "%s/%s:%s" $jobConfig.image.registry $jobConfig.image.repository ( toString $jobConfig.image.tag ) }}
              imagePullPolicy: Always
              command: ["turbo", "run", "script", "--filter=datapuller", "--env-mode=loose", "--"]
              args: ["--script={{ $jobConfig.script | default $jobName }}"]
              envFrom:
                - configMapRef:
                    name: {{ include "bt-app.datapullerName" $root }}-env
                - secretRef:
                    name: {{ include "bt-app.datapullerName" $root }}-secret
          restartPolicy: OnFailure
{{ end }}

---

# ConfigMap for environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bt-app.datapullerName" . }}-env
  labels:
    {{- include "bt-app.datapullerLabels" . | nindent 4 }}
data:
  MONGODB_URI: {{ .Values.mongoUri }}

---

# SealedSecret for sensitive data
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: {{ include "bt-app.datapullerName" . }}-secret
  labels:
    {{- include "bt-app.datapullerLabels" . | nindent 4 }}
spec:
  encryptedData:
    SIS_CLASS_APP_ID: AgB+yHRT9ldfg1VkY/pzbUugv95n4MzOJuEbz+63X/G0LCCHh3PmRMNMDCjUtjoaQvySIBZe9ua9GMwSNseXeSM0GTL4OlXvqLexENp76z3iPoyfRWKd3jcF0fI03YMIZXexISFAraKbLc+wGiUpsfs0u1KknWT5h1q/bYJayErzQ/m4xCzOnu2Wu2S556V8/x2udZIhZzyRRgTmCrqXriD9khRi5hlxUv35RfdfqQTV13M21HftWHe80MleQ2AazB3S1dn/bbkD25ymn/6esH8z3++4R/YpsBy+cv6Jui1Iw8l0vJYbzaeuht3H+vnRl4HsTVcziq/36xU1NpEZ733oHkXVnchVQQOn96VYIJn9Y+JhTo/EFZ28BE3yps84KQmYCv6SPfNdaXsfGXrgpzGgMJ8fxyB5RMMRGRP2+ag1u08Xh1n95a/NgNT6OP6i15JuL4DqclQfQef7E+83IZC38l3A3PFHyqzw/JxQov12s7rI6guM8W1/c+GOGpuGmgy6Tx2KmYXvfsFu3Y8lx2zRO5Cja7BhvvcJTDP1owz4ctRHsqOJsRo5w9eVbOus0yUS3h6BRTth/VnwxEVHdaGXVDCwDkpM9BgZIoTuqw7etBNsUoRVKwN2vV1krQOt5Bjy6L92WoEYPsAoKD7VBim89jyRafNuUR3LwKDozt6NaanBbriS8SZYNtypT2SxGWInYajcVbrs2A==
    SIS_CLASS_APP_KEY: AgABSpfckjFEyknqDSSls8X9tkn0VAtFkL4IiBci/8cKTqTcbdKtmqrkBJtycbn2z1t12pQ0gCg9+EFljDRmYDDXkig1yl75ewPi4l2Uz11Ac30FtTWejgsWlpKV4yf1sW0WY2k6dje+gI62mMgP1nF8omLh2n9skm46p5pCYD3LwMTfOy9O0NSj1ju1brOG0baiDCzg8oK2ll/XAXGSzzHk1rDcukv+ETrKOyR62yZlCCcvynIjFZnNLekuFJNKhUSmHhzanY4xZ2Fg2f5q/B6v1FaD4dniXsmYbTpjZEpCaK3gADqCn/R2wt3OkPfxQ4Ti6+RWNkTvhwuEurM2CYbba7L5qYlUx2TNNESwHvfUONRUAmY7VbMgUZ8+h6r41etDolkJSh3s3v6fQ7ZAIi8NVYK+qxthllg8vVfvTUIghzjhkYyXuq35WoTKPmjUF7vZ+M9jBeCyRXzJCf7GFM+X4hixdUKWUktda7eGDd9pjpl9IFmSoynFk0Beax/tUK7iHDJAwD8QbevHZEn/KtFS31ZynfTguhJXpPi8rQLnrGi7B+gFneJ0I7WW3w0a+Lt/uNNTW6Hpe49T340vkLmyTAEeCIfpe1LQh2ulGGmMS7DdMtEplWZhwbTKMzHfp7xDWe+Zrip8ZRu/qu7BBT2gZj/f2S+lerpf910Ow796iwMMyBCwJ6xGKc08x+jGP1Nzp5TFDRzDq41agvbSmi/GnkUCJ4Lv/mm+3k4FIyN7/Q==
    SIS_COURSE_APP_ID: AgAD7zSeA2oy4CIT9Je6vWLUPDWLrqrDHyXm9+3b0H5p6YU0L5hF5l21z3it2zc/jnuEwU5kyMi0SeUPixzFliRIrQMByMLS+hFrFegSPLCqitpQObXty+XLYBthBuSceLv+19DYg5HCQsPYLAHp+QiQIRo6fjtH373ZZ442Y2Mn3WH0Vs/43Yzk6Z6AmKrnyG/U+8YGMeOvWStn5/eTbZe1HigjTTHa62YfLH96pW58cVqFFdgSNibJNjuKIsaKbF85N5XvIMjdvEz1JLIqUYZgSocTjsJjwbtjDuxNlv+wgRuQYQ+DIjjfL6Mq9rSOIAeDFiR1HjisJ0cfIYB83SQWKtaBtOzYV/cH2tyIusHDkNJ3OTyfduwXwspt8EmsDGBgIu+pnU6gUXotdGSNiClVKb+DrvGxwpAEBK81Rxu5qQ2E7NRB0c6Knbt/FTGwyNEcRws4rFOBEv7u7I1jIKmvTfE67MY8YpBqVHqw2Qf3p32QWaAeJ4BNxLd5h7wGVDFn36qQUPpSlNXX5/1NnIlQo47X58Cot//sgbC0Kfl/jJbihlkWhkiUG2qPhMrCFPBxLN0BErUSqUkQ3fKnvzMnYvP+Y4tZ+5J+m25ngMxe260mUoMhoH+2Y0Re21rEaiLCoDti9opZ31OSiLyDsd8am6rCvNooReGtK+mQKG9tVCqNEjxAoel3X1PaCHVkKjtlkPmyac6f+A==
    SIS_COURSE_APP_KEY: AgCMxRrdzahAW8r5NDMln/ZRHjwCnsH7PzRQ8L8yfWOfnWyv+lPzSyhmz5b3qyYxUA6ZPbsw3M0+T60g+XeLO/bo6QoAPZRyugMFKNDAEg5fqqQd4OeO6DV1EHlrC0597a9wgnd0Ub2kq1vS712/hiAc6+qV2nCR8OFPBIw7AXHnXTke23s/Td5atQXMLY5bCiehZx7X+P713mq7/AHfWsUc/K7rEuSavg5dUS4FMf9dIQfySU4mZV10fOuLFt+VwwMYxp4p7jPD0+Apx47hjzs2MGab/861dt3m0PLOQ388Iz9jV7jvKYsHaBlJKJj7NgPc9F1ZXity2c1reKe4O8mm4bwgbZrguyzaHEmRSO33RnJUiBZXUmZDAbllGWRAglp3hHiIF9XFvdYEyw2Hv4gYkrfO6CUyWyrxQjuXuJn7/JLJJcmpLd3P0fOebqxjAXzC6JsdUjeOig1hyI4bwtMOl3hPcdQ1x4M/wX08BNlgikHykN642oRGDLfVCjOY4lYo/5mGmImcS5Jmfzv29UQfBQzz4mncIILH9DYOaG3wu8GaQr/ehdamdXUO495Ld7QY1EJGxJ8yxEhtKaabZRrtS6Db91xvq2dyGWNkkdO1+++h6MP6oc6S+oxiwDBUlENeS5cQ3v0Ej8Dur0vVcWAie0MiybgNs1SIQZrETZusCXs/s5y40UxM+FFinmveCqgrbcQgzo+GhVStY7rrqsd/AIQ6gDcslKXBgvzV7fZ38w==
    SIS_TERM_APP_ID: AgAwtUcVanOABPOOrrVhWl8g7YkeXNzWMvFgnRE9myjc2cp5/SWJNdia1blPFTwwgVGWcnwTC1htANuJtXjqER19Z5sXmfNY0iowPLQVEsF/tpHeAq75ZrituxgjaOlPeKBNfXAjJS8XcX68miRbP5REUnlYk+FoBfGHUdHhefd249n5jgXwR1IIEUSC0TSnn2KIDvutDMS5e2sEpi4clBwBojSRgiMHO+Y9HsBQlQtTkRU0Sui3cDqjQYRfjR40ato72wl1N6HDgloorYgxRUXu9sGnq6tbIXkOwcRba9y/3p6c4JbBInRSm+H21mV1EYl8WlHlSXulWgnsAO9WGo/dmSmBb0+P1tkWkb4xtavvzVWRu/2qvSIvcjdpzyhfp5JqGVBjNyMh1b3t6Z4gf6f8qn1wfk3w8drNMzMK65XuReVJmUKrWfKDysKiPXa8fTDlcLZCiTghlDDiwjzv2Ie3+pJHlBOaELbmnhfrJZ63+Ir4ezKjJ8HWxHwlkweqUNJDdRXA5sxBY1EhY0zC5sG/ryjVu8jpZdX0APw+VdkA+O9FYrRucBHfDlpkZHx11rkUO2b/1/MVJq6D3Ew6GxfB3DVod4o7WJQAll2jq7a29hkf25URmtvHN8sxkoGuZOpLsITVeYJxevsBwwMWpsFy6KTfHRHYR9g8duoPG5QKZ74fx9bOVezrrTyuCE1k+cQNq9M4Lmt7Aw==
    SIS_TERM_APP_KEY: AgBT6N/VjJ3tHF/fzvIontG+jz5z8pC3fdAAtgW6sHtWGPlO1kBRu5pMRYVw4JRAM+6qyFQI3cDB+1h64WHHjWcqERAYKYLZ/yUL1k8Eg7Rlpdoe8Hu3zeRkYgCJeOwp7dkIeUn7Cy/nukPnEMIKTXk4qdtpJesbYfZJpAtlRT6SFFX97GOwECqDLLZN5UGC6gwt4WBA6D3+FvJZGp30/bTrFwsXsf26dVIr6zThWV0K6BBTtc7C35UzRlOivaoeO/hOxD9Z8MTpyqE/FJdnwH6DKiILyIqk6APcF39Rzafc/S1mNEBTd7lGbIRGRqOuj6mvz6jKahPG+PCZ3zf1NWnmaq1B5vFaC21Fj4qF1WJidKzYKpyfZZXEiExE9CPfgj3cUNeTzXetrXe2B1nWwSHZMkK7y1UJ6Rs/6puPsCbRaSNHCDihZ5aYzYsmh9N6una3+1WtrAEif9T5vW2khQQEicwgforkq+N1kLpbGE3+puYXTJ5vyZlIGBzVHfCkAV/1cCia0k8UfHQnY5TDK5oPq3AYx1Mtrl7yeuwzeLVBAflyOMkiN348pXDooR84kp0hJ/ojVwUXiqJVbD0IKkv5LN4bS0F0JFKb3r00qdvf/h940zG1Cx2wLp1sOm7acirtiROxXdTwAOvt0kxKfx85SUH2sX1aqa43ZbXLJ2Bqm27JIVIyqMkVhgOVwk6Iv1uVmRwqWDzZoo9mVSbkxtdHU+2Lw1ze+GT9vFVndxdcaA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: {{ include "bt-app.datapullerName" . }}-secret
      labels:
        {{- include "bt-app.datapullerLabels" . | nindent 8 }}

---

{{ include "bt-app.datapuller" (list . "courses" .Values.datapuller.courses) }}

---

{{ include "bt-app.datapuller" (list . "sections" .Values.datapuller.sections) }}

---

{{ include "bt-app.datapuller" (list . "classes" .Values.datapuller.classes) }}

---

{{ include "bt-app.datapuller" (list . "cleanup" .Values.datapuller.cleanup) }}
