{{ if not (eq .Values.env "dev") }}
# do not run CronJob in dev environment
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "bt-app.updaterName" . }}
  labels:
    {{- include "bt-app.updaterLabels" . | nindent 4 }}
spec:
  schedule: {{ .Values.updater.schedule }}
  suspend: {{ .Values.updater.suspend }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backend-cron-job
              image: {{ printf "%s/%s:%s" .Values.backend.image.registry .Values.backend.image.repository .Values.backend.image.tag }}
              imagePullPolicy: Always
              command: {{ .Values.updater.command | toJson }}
              ports:
                - containerPort: {{ .Values.backend.port }}
              envFrom:
                - configMapRef:
                    name: {{ include "bt-app.updaterName" . }}-env
                - secretRef:
                    name: {{ include "bt-app.updaterName" . }}-secret
          restartPolicy: OnFailure

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bt-app.updaterName" . }}-env
  labels:
    {{- include "bt-app.updaterLabels" . | nindent 4 }}
data:
  PORT: {{ .Values.backend.port | quote }}
  URL: "http://localhost:5001"
  BACKEND_PATH: {{ .Values.backend.path }}
  GRAPHQL_PATH: "/graphql"
  NODE_ENV: {{ .Values.nodeEnv }}
  MONGODB_URI: {{ .Values.mongoUri }}
  REDIS_URI: {{ .Values.redisUri }}

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: {{ include "bt-app.updaterName" . }}-secret
  labels:
    {{- include "bt-app.updaterLabels" . | nindent 4 }}
spec:
  encryptedData:
    SIS_CLASS_APP_ID: AgCsoV0IeDsbQ1CrUN3ngGSSXx0HlW9qOh0074EpHU3YE9if2D8JWlBpGmpAjDaDG3L749PY22d55QtJAgeHihny85IRt/VElWYqjViv12pvKBOQfLhDOzawaYdA0UQpAA6HA3DNS8nhim1O4bdsfgmQS7Y00KpOnMlRsx6yayvaglDCTCMAgjMR5pZJpE8WhTM2PJMPBHBfx9RBJMYuyrHynftF/jF6l6waPKvgz0Np9hrZA3FucWLYs3+KtKrX5XRGHBw6S9rfGv6FBcIIzz8L4+yzI1O0K46UidST1A9ZLsoXBZ8qxW4bRMBM+dDCFLb1sFyUN5Cn5WTcTyeTvGSdp+bfZQidMYstwR3/3pw9GH6IyrRRI9BTGzdDNE8zs2vDBc4lYg4wnv7Fwz3hQCQKqjJqnIeJKUUh+8eL6F7G09jE4dFNNBZx0qoDfbcb2cDKVTGsstrITqZ+ECzrb+E2l0v9dwFUVjYwbtddes2TACLl3m6mxpdkvYSdtUXY5RWzipjWZitdUT8GrPq8UNd6JdxZe8osd9KrEWQA/i73a9tZEYGkiEAoSfXszt4sGGnrWRrcAcbWs9Ng7aPmGh/LytDZz2hlu1+Mm+tkGkkSWheJPdMWDRLF6JvqzOkrlmevVNTnZa2FnDaKPjECoEzpEp8QYhToP35SRfAWM20j2BmsFdinT5OR1wrgKNPNPMpFkrigW93Qlg==
    SIS_CLASS_APP_KEY: AgCuJdkuSYGdgfljf83p1L7uI9Xk51pLkTXCxE0mNi3MTUnlKfEDW0JCAGC8ohUx33Ey6FiSs1M9d7TRWPxrqwtOAi9Eg3Lo6trRCAIXgUovTJiahXR3DezE/7wl6PphbiAoFec0x1gGDHGvQYhhuwH31SCUONZjxKrTBL4+gcOpjgbOlV3c8XdrM7LNe4ZV5HVtfL7HVUQCMF0zF915YF4A+CtHlkb/Kzfg5EiJVdg3GrbKBkVNmO9R7RXhFblvrDemgVEM7Kud3dd7sQlUOXKC0WuBuXOPVKK+5xsHahNzHwgTJsJV/MWCRby9AhfZyI9t0eQ8SCcIYBvtBXZyKfz6UmltqrMBAHxXpy2rPLEwR2ynmfBB003CfMik/ULojV3fmP2whhhVcVVn0SS04yB3XhkXul0KkoHXe+ZyAr3X3Rt1AWssDWqg2vVhoPQjJ4qA0YVcdbUXQjDecS++APjYDWzpa76l4rGMAaDzSrMBBSfwd+OcfbgEduGIvf9b90Hc6HuH6RcGxMWx66+HHDamK9Ap6+1LqeTnyfWzz3O5rZBC8DkwuLXobmamabBPcDOnAVeVpLXcpV/m9GYhCHN6iVILW8lBxSU9zvrcoMCpOHM3BsPVJKz6FDLWnarY04bnM6CxNhvNLZFyeknHHyO7rQ6VQ8LwAzpqBRB3NfIcbTCwDtYYVjAY4bA6XE/Hl1y8iM1Jsb69oGzkE0ikDM4VD3ELmzRAbUCsgogEkeALFw==
    SIS_COURSE_APP_ID: AgA9OClibfn/q/Iuydr7W7hso3fEf80qJCpG/+aBNg5qqCsXQ8nbkrNyrvdDxE+1DPx2BIebDA6dtpPw38OSEMPMrnbgW6ee84okKd3tg65MkXgUQdq9wvv6+D3gD+FZdTXgNbNFaVUCSnGl8sqkK9ELxv9v6+1U3hPSgqoIDdB0TQpZ4oDBdc9tNMvdnUAfvKnMkn4/v53OSOkvH2eGnT6jMTMkv87aOqPQYYxmU210VTKaWAgKS/+M8n2YYjsoB3FOddibFi63PqF6J6VB89xard4NQxHrAS2QB8QDDAy7ImzUjhZw+T188Vy1C6vnB/oNv42jHNunkfDGmaFdBKdS5pcvuXDKqXT6qEw+39kASiK/72ts1oPVSW5pg1R8BuAzwR+9dge1PrzwnleNOmALV+XQuPhGTGhROtpMpJjBB5gXSx5KwH7Dt8QBFrsVW5Gi9jgs/mMUiVZZNQ/VwINbR2Tmya5x4cZiA6FpjUW75n24MvGmREB9gjbxsI9sdR+hQJOai9vto/nWi8/XtSRuE2wbRTqAigzfKvg6q/xq5yzrtHN0xod/aNyvdxmHLSMJI50cASwivq5xsqE7BTwTqNOMdIfmwPDdvUvUeJFv65e2hB0SfbxUgj2yMlh4y0ctlFV9Eml9cx0xoXiIgDHgDl4WRcNkdfPaFI4yCjLgz9OBNdZieeVr4l2+7bRBhQ2WtKycVdgdEw==
    SIS_COURSE_APP_KEY: AgBEdXE/anO3OX8CtrxKzyuopr5HxpaAc0JEw1Bb3vxFALfKef0tkVrAHcWcGni4IbZBJTHPgo1lwclKWZ+HgLJ+1I2zf9Hk5Wvizn0NZE3Uv5h9OYNypqw9ShuyATcdSC7Slqa41mTU1V+Oo5EdM+eV0ZhpJT23m3s+eoRg9WBLNCjOqV/2dGz55N1mdmlr/Y4x/Shkpo6mWL5hWXtXobduZdI95uusaSQs5/vqQg7SbHpzO10GGxzEFWNJ/hY4AcFuu1SjfNnwboEGPWK1JYDeAhXAKFVYvSSnvw4gkFp6ySaxy8WnGuweQx/HhefX94glrYdhuNi6nWFqGSMP1UWw/AffoeREjkluoCAxiP60NSB94KUME/PSMzBNw3RF50PfC1FB0XC5EOYcqVB/hek0bE9cZ/mRdrLyvMpHXtGRcxA98XTsyP6m8eXe4mtOaWbAF9NhAxEqs/3aQvflxWre3TvOwJJnPLCN02homXrqKoGB/vEsRyaL5NBYvr8wXaB+GSafcOUtngQXb/q1x3YbU0yR0PeEKqoXApgWtPc8lfL+nSQiAndpRm35PAWzgOzgI0SHSWi/8dHrDLZpd8pcgD0hQnIH9uC1ajBRLDLNc0A5EzfU2QA80Ser1ZM14MF15lApCbKftAXxMq3uvnFNFjTv0Hj+ood5Y1srr9D0jQav7M81HBtMugxUyDJ44RjonX239QOLNUJKMGkO2w7CUepZ/HfR3fI4pNJ1YhMxGQ==
    SIS_TERM_APP_ID: AgBlZ1E/ZcYvoFRc9dSn7DWgGAIK//e0q9sa8ZFjf0ZAEuIjEOVqNGSegiyzqqiS/5mXoE/Dcm8DN+oGZRtt7KhfNDbSLKLXUdR5cd2ULxONPIgEmJIzeRKFTCLBezX9YiBSMJBSjJTnd3q3CIqqILclZg5EO/L0/bHVy2oyZ57k4hKaDfEHPUJRwNp5/MKf2eszGw6dO7w1bZI5WFae+Kkz9ToHDdOrtlQTOkoObn85ccgv1T0rM1lmR1RsBcvzxyZk3etQmwa+oounu4mInZsdGI4dX5f2m+v1kHlHk1MNkdGZ/Wdcrjw7SrA09X/jJvr98rp0KCdxAWAwLwjO2jL1dTBcc9doBWOWVIxK5BAG0u36SXfVILuGr97i3dLSLM3gBmFvPnmxA9j7xj/HRlQYBT9OevRofUcy0h3ekpYIbwcRm5n7P6jmH8OoJTdIuLNskw6DlWXCiT9HnPPBY9iZBo6dbffGM+GWV4FoKBLRWCJTiuwgA5VKI93IYMgyDBBXVtayRvMVd2vKrR5xkHSOIuWcc0gdcJwECHFvqtqtaXA/9BdjAi34bG+Gy0smNlpSpNujIeB+tQ6IP42ukQttbRfHoRFsAcfDLWSS7wq9Oa4UqMFbTGmf8cDHjG3WKIGa3JinFyXFkGLvFuVFN2Dg8Ca8G1VmuTN0OrQzVyTmDwUYu34fls8SZYERNz0B5qKNgDCIWpexzA==
    SIS_TERM_APP_KEY: AgBGOBoHZWWL90MIi9jldKJte3zqaH9NTk/b8r11MEqjn9eauud2P6yp8aM2Z+WIMatlkjqgwTVucp0FtA9HHcaxmTc9SedWgaINUN5/chslTGznZ5/SGypEoDeiHyWFxXMMjGSPvSILi+H+RLxQM8ar5z7VqLKsWeI6RsLuvmv23/J4Wd/dk0QA8MR74AqBu/aZV7+muPM60GmT+qL3GCPDlqIxHTyc7qEFr5ZUSCuiuy4Q0Q0I8Tbqx91tBSCEnesaMxUDGMdKpjqYan0gg5yDleaiLJwMefG5bHT/v+IuqY8dYx0D0UN/x00jq8lJp3YfLbQdnSimj1cCcfFpFWNj8JYF6ku06W7Y90DSKP+SzwhkijLVY+ZWAlm7z0yHiwW+m/MGf9VJ/xcQfZjOo/HSqNPsoLx1k9tA2krTL9sWumoClFqo9xIsAK+WVdqqPK8+n+/CBX+t7jbAsu+pimCF/ZPyJW6kQqV3cXzCk+4TisjVpfXPbTDSuk3dw+6u3OocOjmqz9GH1KgMEsNMc8vG9+zprIQOuWHgBLpjgEyVCfbakrNrrYmcG2XbsSBAyMGRy+1wgYQQArr3wnegCy9x1V0IhCBDU0XEkHEJPlbBL1MiThOXXx5B1dePqlTUcHjPJnsun48Dl6cO8DsgwjwXjSWPx+mDUt+LID+urwWD8Q11xXumJSYDdon7E5g6MmVR5fYKoRyWFsbO5s6XarWsz86HPCXoZ+5+TP+EMZ7/Ow==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: {{ include "bt-app.updaterName" . }}-secret
      labels:
        {{- include "bt-app.updaterLabels" . | nindent 4 }}
      name: updater-secrets
{{ end }}
