apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-backup-prod-mongo
  namespace: bt
spec:
  schedule: "0 5 * * *" # Daily at 5 AM
  timeZone: America/Los_Angeles
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 180
      template:
        spec:
          serviceAccountName: bt-k8s-role
          containers:
            - name: backup-prod-mongo
              image: alpine/k8s:1.29.11
              command:
                - sh
                - -c
                - |
                  set -e # Exit immediately if a command fails

                  # Find production MongoDB pod
                  prod_pod=$(kubectl get pods -o custom-columns=NAME:.metadata.name --no-headers -n bt | grep 'bt-prod-mongo')

                  # Dump production MongoDB state
                  echo "Dumping prod MongoDB state..."
                  kubectl exec --namespace=bt \
                    "$prod_pod" -- mongodump --archive=/tmp/prod_backup.gz --gzip
                  kubectl cp --namespace=bt \
                    "$prod_pod:/tmp/prod_backup.gz" /tmp/prod_backup.gz
                  kubectl exec --namespace=bt \
                    "$prod_pod" -- rm /tmp/prod_backup.gz

                  # Upload production MongoDB backup
                  echo "Uploading backup to s3 bucket..."
                  aws s3 cp /tmp/prod_backup.gz s3://$BUCKET_NAME/ \
                    --endpoint-url=https://$ACCOUNT_ID.r2.cloudflarestorage.com \
                    --checksum-algorithm CRC32

                  # Cleanup local files
                  rm /tmp/prod_backup.gz
                  echo "MongoDB backup completed successfully!"
              env:
                - name: ACCOUNT_ID
                  value: ff660bd2dac18c00551ed509d24ef4d7
                - name: BUCKET_NAME
                  value: prod-mongo-backups
              envFrom:
                - secretRef:
                    name: cloudflare-prod-mongo-secret
          restartPolicy: Never

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-prod-mongo-secret
  namespace: bt
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAlY6EsH6KSpyEbvDqodKfFO4UutDKTqO2uRZGk3P7+Mx6HtkP/8K+sc2DBeTXnZtddhPvljvSWevHwjfc4Jc/nrM9Mjm9tB0TTtV8Z/UJX6PxSLfa/BlInFIc/3Sv5C9aR7pTy1ACFnOsa8z/YIYdptw7ts4bFH3S+9EXJlgiziynjaKg3BH2mogFxlu0SYMLlPDQdcdx15qhHgb0RjU223fZHeEuyRSjVRd1LKMLqrF8LS1DdwukNQDMlqEPuORdUPg6pS8MURjhzamcK8GzRVBAF3e2qUK7qM6MZVVjX/IKmImrbO2E3rVyj8tw2WzcFZ1SFUl7FcLKwh2VZ2Oup0SoXK6V2myKjQt2JD9/DJ6jle10uryCfgVKgl4HJeCab6X/knX44ohNvgSIiNZwNcTEOVNoVknFqLX9wQtFqTCAybIzYznQzOpj5LSpe/vlI/PpZ3Q01pJkBgJwMFAOF4Naw5ClXhLXHslMobBgTWNQxE7YAtcMZlYIcoQiBgiCLQfmdm/9Nqjw7x/VF+r2LW/z/15qmRj7LfaRB5hf0AepnRTuQDqm7/g2t+N2DNvgWzckK0teXnjOBnupuxWeInlbMg3Qc2j8caDDlm+5E6BYccdfdsJeDazwD7aI4Q7X4arFkbvaVL4DGUyaOTDDPWJemPFzP6w/z2bH19y4EDsrS+YEqbO0EKVKot0TLOJrlr6jdsmgH4wxDsAK/ZWij5nbylojPia1FPx6vRb99mA==
    AWS_REGION_NAME: AgCAD9QcK/CQjhc5Wbp6x+lK8KDEhcdqfXKwY2tIuZNoILTGCQqY7Ng5zQgLzMZkbXoprTXKhqX/s234A8oIre6NA2EA8MghE1B8/aPrjuDBjDmtPcHGlka3aRiPS1z4WSq1Oo1k4r5LBkZCysCJ5fpKR2XW43DDIet0XcvMuNPMzmfx6vcfgVHvja/l6tdFzd9RD1JJRYInrEqu9Eq6tULpVXXxQqY94YqONaj41YE5NaNXmeIIjGpeQ+EEtw5QLeBGjyQzHSsE5iRVoZOnnUaqezoWbqh/7E8aY1YhptPbrDFXrjzOjQZ7ZTV8El8BY8Cw3E7bYtru//xoF0CKzkXfvWDc2EgM3WU6poJoP6PKcVf6OHtKLN/A6ymuQ5s9Cqg/XCvPGvxkMoLZdqk7WZgeBCsA0h3zrlJ2lIl9Lo5fzrgIHLbBC6gqzWHN/2qPjrXEF0jrEvR1gR224H1AERZ0xLTEZ0UQ/qsZkhLdGhb5q3GeWLa4VZY+VIRAqa3/sBChVPuTMd+6+rr2pa9bzjYaH5ciV5jQK5ALbs7rzH3Vrk5ve7hgOSqS5OC2y97vNFqAhoDbXbPJ/8NU7jwrgGKMB3GzaLBNUcce2IZ7Yl4FBrqU5iNib6L3qq6p+FYGx9KJfsUKeVjt1sI7+m2TXTz/YNe7ZrHFKQYWXiVJC6k5doNKx5B/Nj2YSnQ4rH3+uABO2aiZ47Wk8VA=
    AWS_SECRET_ACCESS_KEY: AgCYLyG+rbY7BbHAswI1Wn5RT39SB0jB+wO3GVNHJW3pnRy/QubWONgD9X4VYgulkzl21+qdTd+h0ftdZ5TR7T8onbmQGbGB0uXZatceHC2BBmt1uP/2E99m9rcMykFFP7mrzpmp+yZzAGLZ/+TLE0E6gs4uK2k7sXCPnBok6ffPQGILzNLAGYSpf7E4o1gaf4xnzVtGTOwdboym54oMS6/Eqp+T9spBghCqj2yb3NSQJ0DEnf5i6HKPi/AaI0+gD0gIOlWwBuWGZQFUdUBnm4I73ltVpCpsct3vzq7/HyTDiVsKnVQvA3o9kNmBp3piRPEGx4MIgfuBCOlFabzl0EpfKVSJ76TaWVgdhy4XG55mqvH9csBMtSw1YqE3TC5YqDthMQngjCJ5fvgDbB9ll1cRCQn57/YKJfdnHhy9kxWIlfPxrpYsWBs/U1SFBEr+AK3//YHfCYRQXUhm3wXM7EPD0N61XD29peCl1IHrtB+qdbpfwoHyMb1abW6aOhZMJ+jtjQ8cGqmAc8OerRMoJUiYUaOjqvaZTPxDF5kc371nmp/1A0LnMNBckzF+g0Z6dB4UCoG141CFec5N4bpwQ1JPGYq4fPBFW73S8bNVHOcmF+u6m3j6+9Iw+kwyyJ1nYuhlqSVuhDNu0CEGWN/MF2cpWwGw9dmPJmLcs3+qE7QJQ0mDTDl//TiyTLiyxXO2q+WWAlvgjBqaTCKzvH4ugnpVIx3u/m+JEhir6KCiC3HOKvSSCpP4Z4bsP7dm2lO8vZFVqA5h2EW155ci7KMYWX0b
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-prod-mongo-secret
      namespace: bt
