apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bt-tls
spec:
  secretName: bt-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: stanfurdtime.com
  dnsNames:
    - stanfurdtime.com
    - "*.stanfurdtime.com"
    - "*.dev.stanfurdtime.com"
