apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Release.Name }}-pool
spec:
  addresses:
  - {{ .Values.ipAddressRange }}

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Release.Name }}-l2
