# Cloudflare Worker
name = "backups-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "PUBLIC_BACKUPS"
bucket_name = "prod-mongo-public-backups"

[[r2_buckets]]
binding = "PRIVATE_BACKUPS"
bucket_name = "prod-mongo-backups"

[[routes]]
pattern = "backups.berkeleytime.com/*"
zone_name = "berkeleytime.com"
