apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bt-tls
spec:
  secretName: bt-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: berkeleytime.com
  dnsNames:
    - berkeleytime.com
    - "*.berkeleytime.com"
    - "*.ocf.berkeleytime.com"
