import { GraphQLResolveInfo } from "graphql";

/**
 * Gets the subfields of the current GraphQL resolver based on its info object.
 * Caution: This function is generated by copilot
 */
export function getChildren(info: GraphQLResolveInfo): string[] {
  const children = info.fieldNodes[0].selectionSet?.selections;
  return children != undefined
    ? children.map((child: any) => child.name.value)
    : [];
}
