{{- if .Values.auth.encryptedData }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: {{ include "bt-mongo.authSecretName" . }}
  labels:
    {{- include "bt-mongo.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- toYaml .Values.auth.encryptedData | nindent 4 }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: {{ include "bt-mongo.authSecretName" . }}
      labels:
        {{- include "bt-mongo.labels" . | nindent 8 }}
{{- end }}
