apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bt-mongo.searchName" . }}-config
  labels:
    {{- include "bt-mongo.labels" . | nindent 4 }}
data:
  # https://www.mongodb.com/docs/search/self-managed/current/installation/docker/
  config.default.yml: |
    syncSource:
      replicaSet:
        hostAndPort: "{{ include "bt-mongo.mongodHost" . }}:27017"
        scramAuth:
          username: "mongot"
          passwordFile: "/etc/mongot-secret/mongot-password"
          authSource: "admin"
          tls:
            enabled: false
      replicationReader:
        readPreference: "secondaryPreferred"
    storage:
      dataPath: "/data/mongot"
    server:
      grpc:
        address: "0.0.0.0:27028"
        tls:
          mode: "disabled"
    metrics:
      enabled: true
      address: "0.0.0.0:9946"
    healthCheck:
      address: "0.0.0.0:8080"
    logging:
      verbosity: INFO
