name_to_standard_name = {
    "RSF": "RECREATIONAL SPORTS FACILITY",
    "CHEIT HALL": "CHEIT CLASSROOM WING",
    "UNIT 1": "UNIT I",
    "UNIT 2": "UNIT II",
    "UNIT 3": "UNIT III",
    "VLSB": "VALLEY LIFE SCIENCES BUILDING"
}
