backend:
  replicas: 2
  image:
    repository: berkeleytime-backend
    tag: latest
  envFile: .env
  sourceCodePath: ./backend/src
redis:
  replicas: 1
  image:
    tag: 6
frontend:
  image:
    repository: berkeleytime-frontend
    tag: latest
mongo:
  replicas: 1
  image:
    tag: 6
  path: "/home/chengmingli/home/berkeleytime/db"
nginx:
  replicas: 1
  image:
    tag: 1.21
  path: "/home/chengmingli/home/berkeleytime/nginx.conf"