export const MODIFY_LIST = 'MODIFY_LIST';
export const RECEIVE_LIST = 'RECEIVE_LIST';
export const MODIFY_SELECTED = 'MODIFY_SELECTED';
export const FILTER = 'FILTER';
export const START_REQUEST = 'START_REQUEST';
export const START_REQUEST_DESCRIPTION = 'START_REQUEST_DESCRIPTION';
export const UPDATE_COURSE_DATA = 'UPDATE_COURSE_DATA';

export const UPDATE_GRADE_CONTEXT = 'UPDATE_GRADE_CONTEXT';
export const GRADE_ADD_COURSE = 'GRADE_ADD_COURSE';
export const GRADE_REMOVE_COURSE = 'GRADE_REMOVE_COURSE';
export const UPDATE_GRADE_DATA = 'UPDATE_GRADE_DATA';
export const UPDATE_GRADE_SELECTED = 'UPDATE_GRADE_SELECTED';
export const GRADE_RESET = 'GRADE_RESET';

export const UPDATE_ENROLL_CONTEXT = 'UPDATE_ENROLL_CONTEXT';
export const ENROLL_ADD_COURSE = 'ENROLL_ADD_COURSE';
export const ENROLL_REMOVE_COURSE = 'ENROLL_REMOVE_COURSE';
export const UPDATE_ENROLL_DATA = 'UPDATE_ENROLL_DATA';
export const UPDATE_ENROLL_SELECTED = 'UPDATE_ENROLL_SELECTED';
export const ENROLL_RESET = 'ENROLL_RESET';

export const OPEN_BANNER = 'OPEN_BANNER';
export const CLOSE_BANNER = 'CLOSE_BANNER';

export const SHOW_MOBILE = 'SHOW_MOBILE';
export const HIDE_MOBILE = 'HIDE_MOBILE';