env: prod
ttl: 86400 # in seconds

host: berkeleytime.com
port: 80

mongoUri: mongodb://bt-prod-mongo-mongodb.bt.svc.cluster.local:27017/bt
redisUri: redis://bt-prod-redis-master.bt.svc.cluster.local:6379
nodeEnv: production

issuer: letsencrypt-prod

frontend:
  replicas: 2

  port: 3000
  path: /

  image:
    registry: docker.io
    repository: octoberkeleytime/bt-frontend
    tag: prod

backend:
  replicas: 2

  port: 5001
  path: /api

  image:
    registry: docker.io
    repository: octoberkeleytime/bt-backend
    tag: prod

updater:
  schedule: "0 0 * * *"
  suspend: false
  command: ["/bin/sh", "-c", "npm run update:catalog;"]
