env: prod
ttl: 24 # in hours

host: berkeleytime.com
port: 80

mongoUri: mongodb://bt-prod-mongo-mongodb.bt.svc.cluster.local:27017/bt
redisUri: redis://bt-prod-redis-master.bt.svc.cluster.local:6379
nodeEnv: production

issuer: letsencrypt-prod

frontend:
  replicas: 2

  port: 3000
  path: /

  image:
    registry: docker.io
    repository: octoberkeleytime/bt-frontend
    tag: prod

  livenessProbe:
    exec:
      command:
        - false
    initialDelaySeconds: 0
    periodSeconds: 1

backend:
  replicas: 2

  port: 5001
  path: /api

  image:
    registry: docker.io
    repository: octoberkeleytime/bt-backend
    tag: prod

  livenessProbe:
    exec:
      command:
        - false
    initialDelaySeconds: 0
    periodSeconds: 1

updater:
  schedule: "0 0 * * *"
  suspend: false
  command: ["npm", "run", "update:catalog", "--workspace=backend"]
