env: prod
ttl: 24 # in hours

host: berkeleytime.com
port: 80

mongoUri: mongodb://bt-prod-mongo-mongodb-0.bt-prod-mongo-mongodb-headless.bt.svc.cluster.local:27017/bt
redisUri: redis://bt-prod-redis-master.bt.svc.cluster.local:6379
nodeEnv: production

issuer: letsencrypt-prod

frontend:
  replicas: 2

  port: 3000
  path: /

  image:
    registry: docker.io
    repository: octoberkeleytime/bt-frontend
    tag: prod

backend:
  replicas: 2

  port: 5001
  path: /api

  image:
    registry: docker.io
    repository: octoberkeleytime/bt-backend
    tag: prod

datapuller:
  suspend: false
  image:
    registry: docker.io
    repository: octoberkeleytime/bt-datapuller
    tag: prod
  cronjobs:
    terms-all:
      schedule: "0 4 1 * *"
      args: ["--puller=terms-all"]
    terms-nearby:
      schedule: "0 4 2-31 * *"
      args: ["--puller=terms-nearby"]

    courses:
      schedule: "5 4 * * *"
      args: ["--puller=courses"]

    # sections-last-five-years:
    #   schedule: "10 4 1 * *"
    #   args: ["--puller=sections-last-five-years"]
    sections-active:
      schedule: "15 4 2-31 * *"
      args: ["--puller=sections-active"]

    # classes-last-five-years:
    #   schedule: "20 4 1 * *"
    #   args: ["--puller=classes-last-five-years"]
    classes-active:
      schedule: "25 4 2-31 * *"
      args: ["--puller=classes-active"]

    # grades-last-five-years:
    #   schedule: "35 4 1 * *"
    #   args: ["--puller=grades-last-five-years"]
    grades-recent:
      schedule: "30 4 2-31 * *"
      args: ["--puller=grades-recent"]

    enrollments:
      schedule: "0/15 * * * *"
      args: ["--puller=enrollments"]
