# Generated by Django 3.1.1 on 2020-11-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
