apiVersion: v1
kind: Service
metadata:
  name: berkeleytime-prod-svc
  namespace: berkeleytime
  labels:
    appName: berkeleytime-prod-svc
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  ports:
  - name: http-bt-port
    port: 5000
    targetPort: 5000
  type: ClusterIP
  selector:
    appName: berkeleytime-prod
