apiVersion: v1
kind: Service
metadata:
  name: frontend-stage-svc
  namespace: berkeleytime
  labels:
    appName: frontend-stage-svc
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  ports:
  - name: http-frontend-port
    port: 3000
    targetPort: 3000
  type: ClusterIP
  selector:
    appName: frontend-stage
