apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: data-update
  namespace: default
spec:
  schedule: "0 9 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: data-update
            image: index.docker.io/berkeleytime/berkeleytime:latest
            imagePullPolicy: Always
            command:
            - ./update-data.sh
            env:
            - name: PYTHONUNBUFFERED
              value: "0"
            - name: GET_HOSTS_FROM
              value: dns
            - name: ENVIRONMENT_NAME
              value: PRODUCTION
            envFrom:
            - configMapRef:
                name: django-configs
            - secretRef:
                name: aws
            - secretRef:
                name: google
            - secretRef:
                name: sis
            - secretRef:
                name: sendgrid
            - secretRef:
                name: sentrydsn
          restartPolicy: OnFailure
