apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: data-update
  namespace: berkeleytime
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: data-update
            image: berkeleytime/berkeleytime:latest
            imagePullPolicy: Always
            command:
            - ./update-data.sh
          restartPolicy: OnFailure