name: 
  Deploy to Dev

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH Key
      uses: webfactory/ssh-agent
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}
    - name: SSH into Hozer
      run: |
        ssh root@hozer-51.ocf.berkeley.edu "echo 'test'"
