name: 
  Deploy to Dev

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH client
      run: apt-get update && apt-get install -y openssh-client

    - name: Run SSH command
      run: |
        ssh -i ${{ secrets.SSH_KEY }} root@hozer-51.ocf.berkeley.edu "echo test"
