name: 
  Deploy to Dev

on:
    repository_dispatch:
      types: [trigger-workflow]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker Image
      run: docker build -t berkeleytime-backend ./backend/
    - name: Tag Docker Image
      run: docker tag berkeleytime-backend ${{ secrets.DOCKER_USERNAME }}/berkeleytime-backend:${{ github.sha }}
    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/berkeleytime-backend:${{ github.sha }}
    - name: Echo Params
      run: |
        echo "Subdomain: ${{ github.event.client_payload.param1 }}"
        echo "Time to Live: ${{ github.event.client_payload.param2 }}"
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: hozer-51.ocf.berkeley.edu
        username: root
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          helm install bt-dev-app-${{ github.sha }} ./app --namespace=bt \
            --set host=${{ github.event.client_payload.param1 }}.stanfurdtime.com \
            --set mongoUri=mongodb://bt-dev-mongo-mongodb.bt.svc.cluster.local:27017/bt \
            --set redisUri=redis://bt-dev-redis-master.bt.svc.cluster.local:6379 \
            --set nodeEnv=development
          helm release ttl bt-dev-app-${{ github.sha }} --set='${{ github.event.client_payload.param2 }}'
