name: 
  Deploy to Dev

on:
    repository_dispatch:
      types: [trigger-workflow]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Echo Params
      run: |
        echo "Subdomain: ${{ github.event.client_payload.param1 }}"
        echo "Time to Live: ${{ github.event.client_payload.param2 }}"
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: hozer-51.ocf.berkeley.edu
        username: root
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: whoami
