name: 
  Deploy to Staging

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Hozer
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: hozer-51.ocf.berkeley.edu
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: | 
            cd /berkeleytime
            git checkout master
            git pull
            docker compose up --build -d
            docker tag berkeleytime-backend octoberkeleytime/bt-backend:latest
            docker tag berkeleytime-frontend octoberkeleytime/bt-frontend:latest
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker push octoberkeleytime/bt-backend:latest
            docker push octoberkeleytime/bt-frontend:latest
            kubectl rollout restart deployment bt-staging-app-backend
            kubectl rollout restart deployment bt-staging-app-frontend