name: 
  Deploy to Staging

on:
  push:
    branches: [ master ]
  workflow_run:
    workflows:
      - "Build Frontend"
      - "Build Backend"
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa root@hozer-51.ocf.berkeley.edu << EOF
            cd /berkeleytime
            git checkout master
            git pull
            docker compose up --build -d
            docker tag berkeleytime-backend octoberkeleytime/bt-backend:latest
            docker tag berkeleytime-frontend octoberkeleytime/bt-frontend:latest
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker push octoberkeleytime/bt-backend:latest
            docker push octoberkeleytime/bt-frontend:latest
            kubectl rollout restart deployment bt-staging-app-backend
            kubectl rollout restart deployment bt-staging-app-frontend
          EOF
