name: 
  Deploy to Prod

on:
  repository_dispatch:
      types: [trigger-workflow]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Backend Image
      run: docker build -t berkeleytime-backend ./backend/
    - name: Tag Backend Image
      run: docker tag berkeleytime-backend ${{ secrets.DOCKER_USERNAME }}/berkeleytime-backend:prod
    - name: Push Backend Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/berkeleytime-backend:prod
    - name: Build Frontend Image
      run: docker build -t berkeleytime-frontend ./frontend/
    - name: Tag Frontend Image
      run: docker tag berkeleytime-frontend ${{ secrets.DOCKER_USERNAME }}/berkeleytime-frontend:prod
    - name: Push Frontend Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/berkeleytime-frontend:prod
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: hozer-51.ocf.berkeley.edu
        username: root
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
            kubectl rollout restart deployment bt-prod-app-backend
            kubectl rollout restart deployment bt-prod-app-frontend
