name: Build and Push Images and Charts

on:
  workflow_call:
    inputs:
      image_tag:
        description: "Image build tag"
        required: true
        type: string
      chart_ver:
        description: "Chart build tag"
        required: true
        type: string

jobs:
  build-push-image:
    name: Build and Push Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [backend, frontend]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Image with Tag
        run: |
          docker build --no-cache --platform=linux/amd64 --target ${{ matrix.image }}-prod --tag "${{ secrets.DOCKER_USERNAME }}/bt-${{ matrix.image }}:${{ inputs.image_tag }}" .
          docker push "${{ secrets.DOCKER_USERNAME }}/bt-${{ matrix.image }}:${{ inputs.image_tag }}"

  build-push-chart:
    name: Build and Push Helm Chart
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart: [app]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: infra

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Helm Chart
        run: |
          cd ./infra
          helm registry login registry-1.docker.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          helm dependency update ${{ matrix.chart }}
          helm package ${{ matrix.chart }} --version ${{ inputs.chart_ver }}
          helm push bt-${{ matrix.chart }}-${{ inputs.chart_ver }}.tgz oci://registry-1.docker.io/${{ secrets.DOCKER_USERNAME }}
