name: SSH and Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: "Github action environment to deploy within"
        required: true
        type: string
      name:
        description: "Helm chart installation name"
        required: true
        type: string
      version:
        description: "Helm chart version"
        required: true
        type: string
      values:
        description: "Helm chart override values (yaml)"
        required: true
        type: string

jobs:
  deploy:
    name: SSH and Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: SSH and Helm Install
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e  # Exit immediately if a command fails

            # Upgrade helm chart, or install if not exists
            helm upgrade ${{ inputs.name }} oci://registry-1.docker.io/octoberkeleytime/bt-app \
              --install \
              --version=${{ inputs.version }} \
              --namespace=bt \
              --values <(echo "${{ inputs.values }}")

            # Check container status
            kubectl rollout status --timeout=180s deployment ${{ inputs.name }}-backend
            kubectl rollout status --timeout=180s deployment ${{ inputs.name }}-frontend
