name: Generate Helm Diffs for PR

on:
  workflow_call:
    inputs:
      pr_number:
        description: 'PR number to generate diff for'
        required: true
        type: string

jobs:
  helm-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Details
        id: pr
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.name,
              pull_number: context.issue.number
            });
            return { 
              ref: pr.head.ref,
              sha: pr.head.sha
            };

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.pr.outputs.ref }}

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: '3.10.2'

      - name: Install Helm Diff Plugin
        run: helm plugin install https://github.com/databus23/helm-diff

      - name: Add Helm Repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add bitnami-labs https://bitnami-labs.github.io/sealed-secrets/
          helm repo add cert-manager https://charts.jetstack.io
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo add metallb https://metallb.github.io/metallb
          helm repo add oauth2-proxy https://oauth2-proxy.github.io/manifests
          helm repo update

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.HELM_DIFF_KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Generate Diffs
        id: diff
        run: |
          {
            echo 'DIFF<<EOF'
            echo "### Helm Diff Results"
            echo
            echo "#### Base Chart"
            echo '```'
            helm diff upgrade bt-base ./infra/base \
              --install \
              --namespace=bt || true
            echo '```'
            echo
            echo "#### App Chart"
            echo '```'
            helm diff upgrade bt-prod-app ./infra/app \
              --install \
              --namespace=bt \
              --set host=stanfurdtime.com \
              --version=1.0.0 || true
            echo '```'
            echo EOF
          } >> $GITHUB_ENV

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          script: |
            const diff = process.env.DIFF;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.name,
              issue_number: context.issue.number,
              body: diff
            });











