name: Lint

on:
  workflow_dispatch:
  push:
    branches: ["main", "gql"]
  pull_request:
    branches: ["main", "gql"]

jobs:
  build:
    name: Lint, generate types, and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # setup nodejs
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      # cache node_modules
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Generate types
        run: npm run generate

      - name: Build
        run: npm run build
