name: Linting

on:
  push:
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install latest node version
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: npm install and lint
        working-directory: ./backend
        run: |
          npm install
          npm run lint
