name: Linting

on:
  push:
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npm install and lint
        working-directory: ./backend
        run: |
          npm install
          npm run lint
