name: Restore Prod Mongo

on:
  workflow_dispatch:
    inputs:
      restore_date:
        description: "Date of backup to restore (YYYYMMDD)"
        required: true
        type: string

jobs:
  restore-mongo:
    name: SSH and Restore Prod MongoDB State
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Reset MongoDB
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e  # Exit immediately if a command fails

            # Create Mongo job from mongo-restore
            restore_date="${{ github.event.inputs.restore_date }}"
            kubectl create job --from=cronjob/bt-base-restore-prod-mongo bt-base-restore-prod-mongo-ga-manual \
              --dry-run=client -o json \
              | jq ".spec.template.spec.containers[0].env += [{\"name\": \"RESTORE_DATE\", \"value\": \"$restore_date\"}]" \
              | kubectl apply -f -
            echo "MongoDB restore from $restore_date scheduled."

            # Wait for job_pod log output
            job_pod=$(kubectl get pods -o custom-columns=NAME:.metadata.name --no-headers -n bt | grep 'bt-base-restore-prod-mongo-ga-manual')
            kubectl wait --for=condition=ready pod/$job_pod -n bt --timeout=30s
            kubectl logs -f $job_pod -n bt
